### ISSUE TITLE
Builders wand message error

### ISSUE THREAD

**Issue by poikcue** [VolmitSoftware/Adapt#103]
### Problem

1. Install adapt
2. Unlock "Builders wand" (at Architect page)
3. If the number of blocks in hand is not enough to use builders wand. It should send a message.
4. There is a problem with this text

### Solution (if any)

en_US.json key: Architect.Placement
In general, it should be lore1 + num + lore2.
But there seems to be some problems here. It is lore2 + num + lore2

### Minecraft Version

1.19

### Adapt Version

1.0.8

### Log

https://s1.ax1x.com/2022/09/04/vo75BF.png

**Comment by poikcue** [comment]
Sorry to submit the picture. But, it has no logs.

**Comment by NextdoorPsycho** [comment]
oh shit, thank you, Fixed
