### ISSUE TITLE
Wither skull throw not work

### ISSUE THREAD

**Issue by poikcue** [VolmitSoftware/Adapt#107]
### Problem

1. Install Adapt
2. Learn "Wither skull throw"
3. Give yourself a Wither Skeleton Skull.
4. Left-click
5. The ability doesn't work, but the sound effect works normally (I can still hear the sound effect even if I already unlearn it).

By the way, after installing the plugin and learn for the first time, it works normally and the countdown also works normally. After the countdown, it will not work (like step 5)

### Minecraft Version

1.19

### Adapt Version

1.0.9

### Log

Sorry, but there are no logs.

**Comment by NextdoorPsycho** [comment]
Latest working
