### ISSUE TITLE
Could not pass event EntityDeathEvent to Adapt v1.0.10-1.19.2

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#111]
### Problem

1. Install Adapt.
2. No configuration changed, everything default.
3. Console prints the following error:
- [Wed 07:47:47 ERROR Minecraft] Could not pass event EntityDeathEvent to Adapt v1.0.10-1.19.2
java.lang.ArrayIndexOutOfBoundsException

### Minecraft Version

1.19.1

### Adapt Version

1.0.10 for 1.19.2

### Log

https://mclo.gs/gcPFQ6h

**Comment by NextdoorPsycho** [comment]
This log was unhelpful as when someone asks you for a log they usually want a full log, not a truncated snippet. this was a truncated snippet. can you actually send a full log?

Additionally i was unable to replicate it so it might be a plugin incompatibility on your end (where me seeing a full log would have been helpful) i can patch it but id need to know what you are using / how you are causing it to be able to replicate it
