### ISSUE TITLE
Critical exp dupe bug, should hide this report maybe

### ISSUE THREAD

**Issue by PlopHat** [VolmitSoftware/Adapt#120]
Gif it's self explanatory I guess. have no way to get the logs bc i'm not anythiing from the owner.
You can do it by having full inventory, then shift clic, items cannot be processed but adapt gives xp anyway, pretty op with xp refund ability

![buugCraftingXP](https://user-images.githubusercontent.com/41564958/189030215-21dba65f-07b3-480a-8854-0c4b4d789f9d.gif)

Adapt version: Adapt-1.0.11-1.19.2

Hope u can replicate c:

**Comment by NextdoorPsycho** [comment]
Fixed
