### ISSUE TITLE
Speech Skill

### ISSUE THREAD

**Issue by Foxersthe** [VolmitSoftware/Adapt#125]
A speech skill for using with villagers that influences prices of buying and selling goods. Maybe one ability would be the ability to gift items to villagers to improve their relations with you. Maybe it could make villagers 'happy' to make breeding them easier too?

**Comment by dinobossytnew** [comment]
+1

**Comment by NextdoorPsycho** [comment]
On dev branch, 
With the skill you can exchange XP for Cheaper trades with Villagers
