### ISSUE TITLE
Toggle Particles Per Skill

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#131]
### Problem

When players join a server for the first time, they get spammed with "Discovery XP" messages and constant particle effects. It would be super awesome if we could have a toggle in the config file per skill to choose whether a skill sends messages/particle effects when XP is gained. 

Not really necessary for _every_ skill, but would be super useful for the Discovery skill in particular since that is the spammy one.

### Minecraft Version

1.19.2

### Adapt Version

1.0.12-1.19.2	

### Log

N/A

**Comment by NextdoorPsycho** [comment]
The Discovery Skill is the only thing that spams Particles like that, what ill do is add a config system that just looks at what is specified in every skill / Adaptations. 

Its not hard at all, in fact i could do it in an afternoon, its just a time consuming task. not a hard one

**Comment by NextdoorPsycho** [comment]
Done, will be in next update
