### ISSUE TITLE
Protected region does not cancel XP gain. 

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#132]
### Problem

If you have a region setup using WorldGuard, players are unable to break blocks. (Intended)
However, they still get skill XP for breaking said block, even though no block was broken server-side. (Probably shouldn't be intended)

This same issue applies for other land protection plugins that prevent block-break, such as Factions. 

### Minecraft Version

1.19.2

### Adapt Version

1.0.12-1.19.2	

### Log

N/A

**Comment by Armin231** [comment]
fixed with this commit https://github.com/VolmitSoftware/Adapt/commit/fc1da1f816f434801f0e91f2bcfa381e21528350
Should be available with the upcoming update
