### ISSUE TITLE
Could not pass event. 

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#136]
### Problem

Updated Adapt to 1.1.0-1.19.2 and the following errors started popping up in console:

**Could not pass event PlayerDeathEvent to Adapt v1.1.0-1.19.2**
https://mclo.gs/yUi1dF7#L734
https://mclo.gs/yUi1dF7#L770
https://mclo.gs/yUi1dF7#L815

Could not pass event EntityDeathEvent to Adapt v1.1.0-1.19.2
https://mclo.gs/yUi1dF7#L782
https://mclo.gs/yUi1dF7#L850
https://mclo.gs/yUi1dF7#L861
https://mclo.gs/yUi1dF7#L866
https://mclo.gs/yUi1dF7#L870

Could not pass event FurnaceSmeltEvent to Adapt v1.1.0-1.19.2
https://mclo.gs/yUi1dF7#L872

### Minecraft Version

1.19.2

### Adapt Version

1.1.0-1.19.2

### Log

https://mclo.gs/yUi1dF7

**Comment by ZocharyJ** [comment]
Data file of a player throwing these errors:
https://mclo.gs/Bpbrl8K

**Comment by NextdoorPsycho** [comment]
Maybe Fixed on latest, Thank you for the help, reopen if you still have this issue
