### ISSUE TITLE
[Bug]Error in server

### ISSUE THREAD

**Issue by srlss123** [VolmitSoftware/Adapt#140]
### Problem

1. Install Adapt
2. Observe the error

### Minecraft Version

1.19

### Adapt Version

v1.0.13

### Log

https://pastebin.ubuntu.com/p/jvMdgq92cr/

**Comment by Armin231** [comment]
> ### Problem
> 1. Install Adapt
> 2. Observe the error
> 
> ### Solution (if any)
> _No response_
> 
> ### Minecraft Version
> 1.19
> 
> ### Adapt Version
> v1.0.13
> 
> ### Log
> https://pastebin.ubuntu.com/p/jvMdgq92cr/

Use the latest versions of adapt. 1.0.13 is a bit outdated
