### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.volmit.adapt.api.xp.SpatialXP.getMs()"

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#148]
### Problem

Updated to the latest version available, all was well until it wasn't. I have no idea what even triggered this, sorry I can't provide more information.

Latest.log attached.

### Minecraft Version

1.19

### Adapt Version

1.1.4 for 1.19.2

### Log

https://pastebin.com/HdXZ7e1g

**Comment by NextdoorPsycho** [comment]
Should be fixed on latest
