### ISSUE TITLE
Could not pass event EntityDeathEvent to Adapt v1.1.4-1.19.2

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#150]
### Problem

Line 1324: [07:42:05] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Adapt v1.1.4-1.19.2
Line 1371: [07:44:39] [Server thread/ERROR]: Could not pass event FurnaceSmeltEvent to Adapt v1.1.4-1.19.2

Error starts out of nowhere, and seemingly at random.

### Minecraft Version

1.19

### Adapt Version

v1.1.4-1.19.2

### Log

https://pastebin.com/dLtGUhk5

**Comment by NextdoorPsycho** [comment]
Probably Fixed on latest
