### ISSUE TITLE
XP Balance

### ISSUE THREAD

**Issue by poikcue** [VolmitSoftware/Adapt#154]
I am not a Java developer. So I don't know if this can be done in bukkit's API. However, this should balance XP.
1. Reduce XP to 1/2 when killing mobs that spawned from spawner (Add a config that server owner can modify it.)
2. if someone killed mobs over 20 (or 30?) per minute, then reduce XP to 1/4 or lower (Add a config that server owner can modify it.)
3. Some player use modded client then go afk to get a huge number of xp. The more time they waste for afk, the less XP they will get.

Farming same as above.
Implementing the above may be very hard, but it may be a good way to balance XP.

**Comment by NextdoorPsycho** [comment]
I made it so Mobs that are spawner created drop HALF Xp by default,  and you can modify this if you want. its on the development branch and will likely be in the next update. Thank you for the suggestion
