### ISSUE TITLE
v1.1.6-1.19.2 Console Errors

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#157]
### Problem

1. Line 1259: [07:34:31] [Iris 59/WARN]: java.io.UTFDataFormatException: malformed input around byte 17
2. Line 1479: [08:06:23] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Adapt v1.1.6-1.19.2
3. Line 1598: [08:12:32] [Server thread/ERROR]: Could not pass event FurnaceSmeltEvent to Adapt v1.1.6-1.19.2

Multiple errors since updating to 1.1.6, general player usage. 

### Minecraft Version

1.19

### Adapt Version

v1.1.6-1.19.2

### Log

https://pastebin.com/q0CyCGQD

**Comment by NextdoorPsycho** [comment]
Try latest!
