### ISSUE TITLE
Dependencies, Requirements, and Restrictions

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Adapt#16]
Configurable Skill dependencies (ie: 2 void perks, and a mining)
You mist have maxed blink, and mining to be able to do .....
You cant have Blink, and wall-walker

- [ ] Dependencies 
- [ ] MYSQL / SQL  of some kind system
- [ ] Requirements
- [ ] Proper Hotloading (50%)
- [ ] Proper Command System (50%)
- [X] restructions
- [X] bonuses

**Comment by Armin231** [comment]
Closing cause this would be the proper place https://github.com/orgs/VolmitSoftware/projects/3
