### ISSUE TITLE
Could not pass event * to Adapt v1.1.9-1.19.2

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#165]
### Problem

1. Line 1646 FurnaceSmeltEvent*
2. Line 1700 EntityDeathEvent*

### Minecraft Version

1.19

### Adapt Version

v1.1.9-1.19.2

### Log

https://pastebin.com/bA4Ru4FB

**Comment by NextdoorPsycho** [comment]
This is why i hate citizens

**Comment by NextdoorPsycho** [comment]
SHould be fixed
