### ISSUE TITLE
Bookshelf interact issue

### ISSUE THREAD

**Issue by InternetVet** [VolmitSoftware/Adapt#170]
### Problem

When holding food and right clicking the bookshelf
it causes the player to "auto eat" whatever it is they are holding

No matter if its a raw chicken or golden apple... 

after the eating starts there is no hope xD

### Minecraft Version

1.19

### Adapt Version

1.2.0

### Log

no a loggable  issue

**Comment by NextdoorPsycho** [comment]
**after the eating starts there is no hope**
i want that on a T-shirt

**Comment by NextdoorPsycho** [comment]
on dev branch
