### ISSUE TITLE
Placeholders 

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Adapt#175]
### Adding, Removing, or Changing

Adding

### Type of Modification

Some placeholders that would be nice to have.

### What are you trying to modify

Here is a list of some that I would like to see in game.

**Displays the current skill level**
%agility_level%
%architect_level%
%axe_level%
%brewing_level%
%crafting_level%
%discovery_level%
%enchanting_level%
%excavation_level%
%herbalism_level%
%hunter_level%
%nether_level%
%pickaxe_level%
%ranged_level%
%rift_level%
%seaborn_level%
%stealth_level%
%swords_level%
%taming_level%
%unarmed_level%

**Other**
%dynamic_skill_xp% ( handy for scoreboards it makes a pop up like for example +34 agility xp and after 2s it will disappear and it will go back to a blank line  )

### Alternatives

*

**Comment by NextdoorPsycho** [comment]
Done and did more
