### ISSUE TITLE
Startup logo like the Iris Plugin

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Adapt#176]
### Adding, Removing, or Changing

Adding

### Type of Modification

Console startup logo like what iris has

### What are you trying to modify

<img width="1111" alt="Schermafbeelding 2022-09-16 om 13 59 15" src="https://user-images.githubusercontent.com/107539181/190634209-6e77a335-0a52-4587-a550-f716bad04bcb.png">

this but one made for adapt 

### Alternatives

*

**Comment by NextdoorPsycho** [comment]
![image](https://user-images.githubusercontent.com/29320316/190703243-be83bbe3-dad8-4121-90a9-26cbebf67e51.png)
