### ISSUE TITLE
Shared Playerdata across server networks

### ISSUE THREAD

**Issue by Armin231** [VolmitSoftware/Adapt#18]
Make it so levels and skills are networkwide and not serverwide

**Comment by NextdoorPsycho** [comment]
Why would we install anything on the bungeecord when you could just install adapt on both servers? if you do that you can have different configs. OR did you mean you wanted to have Shared PlayerData

**Comment by Armin231** [comment]
> Why would we install anything on the bungeecord when you could just install adapt on both servers? if you do that you can have different configs. OR did you mean you wanted to have Shared PlayerData

Yea exactly. A shared playerdata. So you have the same progress on both servers. The possibility to not start all over again.

**Comment by NextdoorPsycho** [comment]
https://www.spigotmc.org/resources/filesync-sync-files-across-your-servers.93054/
imma close this issue, because plenty of plugins that do a better job exist, but ill keep this in mind for things like hosting adapt on bungie or minimal modes
