### ISSUE TITLE
Missing space in translation

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#187]
### Problem

Use the architect's "builders wand" skill with insufficient blocks and observe the message in the chat
![Screenshot_7](https://user-images.githubusercontent.com/53750990/190877085-65823ca3-f465-4a66-abec-d3d129ca0f3d.png)

### Solution (if any)

Probably here https://github.com/VolmitSoftware/Adapt/blob/dd6f580ab8e0ddca157a2d655c977245d4652749/src/main/java/com/volmit/adapt/content/adaptation/architect/ArchitectPlacement.java#L122
Or just editing the language file

### Minecraft Version

1.19.2

### Adapt Version

1.2.1-1.19.2

### Log

is this needed....

**Comment by NextdoorPsycho** [comment]
Fixed on dev
