### ISSUE TITLE
Can use skills in GriefPrevention claims even if requireBuildPermissionToUseSkills is set to true

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#188]
### Problem

Install adapt and griefprevention
claim an area
try to use skills inside of it (when not having permission to build with another account or something)
see that you can use skills

Reference: https://gyazo.com/f43169359f94f982f57096822a32bc0f 

### Solution (if any)

Check for griefprevention claims using the GP API

(GriefPrevention.instance.dataStore.getClaimAt would be possible) 

### Minecraft Version

1.19.2

### Adapt Version

1.2.1-1.19.2

### Log

https://pastebin.com/CxR79mtr

**Comment by NextdoorPsycho** [comment]
So im going to remove this setting because i realized that spamming blockbreak events on player move might not be the best idea. Adapt will block breaking  restrictions but movement will not as i have no way of detecting if im within range of a claim, though i will check it
