### ISSUE TITLE
"Dropped" debug message in chat.

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#194]
### Problem

1. Install Adapt 1.3.1-1.19.2
2. Users now see a "Dropped" message in chat every time an entity is dropped from BlockBreak event.

https://imgur.com/a/m1QDFLz

### Minecraft Version

1.19.2

### Adapt Version

1.3.1-1.19.2

### Log

https://pastebin.com/3YKUE703

**Comment by NextdoorPsycho** [comment]
Oops that’s a debugging thing I forgot to remove

**Comment by Armin231** [comment]
Fixed with the next version
