### ISSUE TITLE
Make exp boosts customizable

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#197]
### Adding, Removing, or Changing

Changing

### Type of Modification

I want to decide when i want exp boosts to be enabled or not

### What are you trying to modify

The way I would implement this is stop forcing a exp boost when players join and be able to execute a command with given exp boost parameters so i can reward players for quests etc.

### Alternatives

Removing the lines of code manually

**Comment by xmorose** [comment]
Making the join-exp-boost configurable would also work, having disabling, enabling, exp boost duration, boost amount etc.

**Comment by NextdoorPsycho** [comment]
If you want to reward players give them flat XP, not a boost, boost is abusable
/iris adapt item experience <skill> <value>
