### ISSUE TITLE
Ore Duplication

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#202]
### Problem

1. Have the chisel adaptation
2. Have pickaxe with silk touch + mending next to an active mob farm
3. Have multiple diamond ores in off hand and one placed in front of you
4. Spam/hold right-click on placed ore
5. Diamond ore is chiselled and picked up, and immediately placed back down, not losing the ore but consistently getting dupe diamonds
6. ???
7. Profit

### Minecraft Version

1.19.2

### Adapt Version

1.3.2-1.19.2	

### Log

n/a

**Comment by NextdoorPsycho** [comment]
Step 6 is my favorite, Fixed on dev
