### ISSUE TITLE
Cost for resetting skilltrees

### ISSUE THREAD

**Issue by ZocharyJ** [VolmitSoftware/Adapt#203]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to be able to set a cost for resetting skills

### What are you trying to modify

The way I would implement this is to have it cost 2x (configurable) knowledge to "reset" a skill.

Eg, if an adaptation costs 1 knowledge to unlock, have it cost 2 knowledge to reset.

### Alternatives

N/A

**Comment by NextdoorPsycho** [comment]
Added a hardcore loss in settings
