### ISSUE TITLE
Disabling Advancements

### ISSUE THREAD

**Issue by Armin231** [VolmitSoftware/Adapt#205]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to make the Advancement system toggleable

### What are you trying to modify

The way I would implement this is by adding a setting in the config.

According to a user that is having a highly customized Advancement system on his server adapt isn't fitting in there and therefore he wants to disable it.

### Alternatives

Dunno

**Comment by NextdoorPsycho** [comment]
Added
