### ISSUE TITLE
Error msg when mining stone with a pickaxe

### ISSUE THREAD

**Issue by Armin231** [VolmitSoftware/Adapt#228]
### Problem

1. Install Adapt
2. Do commands
3. Mine stone with pickaxe
4. See the error

### Solution (if any)

Look at it and if its a bug fix it

### Minecraft Version

1.19.2

### Adapt Version

v1.3.7-1.19.2

### Log

https://mclo.gs/FMJMWX8

**Comment by NextdoorPsycho** [comment]
Dont give yourself haste 60 and complain when plugins cant find blocks that you sent to the shadow realm
