### ISSUE TITLE
No Such Element issue

### ISSUE THREAD

**Issue by InternetVet** [VolmitSoftware/Adapt#243]
### Problem

I updated the server to newest update and joined. 

After about 8 minutes in game i got this in console

https://pastebin.com/yTxp8vjs

### Minecraft Version

1.19.2

### Adapt Version

1.4.0

### Log

https://pastebin.com/yTxp8vjs

**Comment by NextdoorPsycho** [comment]
Cant help you, this is not a full log, make a new issue with the full log
