### ISSUE TITLE
NoSuchElementException issue

### ISSUE THREAD

**Issue by InternetVet** [VolmitSoftware/Adapt#247]
### Problem

Joined my server after its been idle for hours
get this in console after joining 

not sure the cause

### Minecraft Version

1.19.2

### Adapt Version

1.4.1

### Log

https://sharetext.me/3co2id5txo

**Comment by NextdoorPsycho** [comment]
Is this a joke?![image](https://user-images.githubusercontent.com/29320316/193698429-3bee5d7b-c334-464f-88f1-fcf51c13da8d.jpeg)
Use a full log and one that doesn't expire
