### ISSUE TITLE
When using translated files zh_ CN.json

### ISSUE THREAD

**Issue by RecanLive** [VolmitSoftware/Adapt#248]
### Problem

1. Install Adapt...
2. i run command /adapt item exeperience
3. kill eneity

### Solution (if any)

It should be caused by translating files or other

### Minecraft Version

1.19.2

### Adapt Version

1.4.1

### Log

https://pastebin.com/AUcuCBX5

**Comment by poikcue** [comment]
zh_CN.json `axes`部分少一个技能，然后`penalty`部分少描述和一个名称。我不知道为什么gitlocalize显示100%，我看一下pr

**Comment by NextdoorPsycho** [comment]
Should be fixed on latest

**Comment by RecanLive** [comment]
> 
好的 我先试试能用不
