### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by RecanLive** [VolmitSoftware/Adapt#255]
### Problem

1. i ues the latest version 1.4.2
2. player can also use armor frame brush level or experience
3. Could not pass event InventoryClickEvent to Adapt v1.4.2-1.19.2

### Solution (if any)

i dont know..

### Minecraft Version

1.19.2

### Adapt Version

1.4.2

### Log

https://pastebin.com/qyfeCB4q

**Comment by NextdoorPsycho** [comment]
this should be something you can ignore, but ill see what is causing it and what I can do, Are you able to cause it in a specific way? like in a particular inventory or something?
