### ISSUE TITLE
Skill milestone announcements

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#257]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to have a possibility to configure server-wide announcements in chat when a player hits a skill milestone

### What are you trying to modify

Would be great to have a configurable system that would allow owners to set up messages in chat that basically get triggered when players reach certain levels in certain skills. Things like 

**MagicPsycho** has reached level **20** in **Axes**!

Messages like these are kinda nice when having a community like i do for example, job-levels etc. already get announced so the new adaptations would be nice too. :D

### Alternatives

Ehh well modifying it myself, thats about it. I dont think theres a simple way to trigger thouse outside of editing the code directly.

**Comment by NextdoorPsycho** [comment]
You can already do this. We support PAPI
And you can see what level someone is in a skill. Look at the papi placeholders. and im sure you can find / I can make a plugin for you  that checks that. open a ticket on discord and @ me if you need more help
