### ISSUE TITLE
Could not pass event InventoryClickEvent to Adapt v1.4.2-1.19.2

### ISSUE THREAD

**Issue by doitliketyler** [VolmitSoftware/Adapt#259]
### Problem

Just reporting a console error I'm getting. Not sure what action is causing it but am seeing it pop up periodically while folks are playing

1. Install Adapt
2. Join server with players
3. Observe console
4. See this error: https://pastebin.com/raw/w0RC9wAV

### Minecraft Version

1.19.2

### Adapt Version

v1.4.2-1.19.2

### Log

https://pastebin.com/raw/w0RC9wAV

**Comment by NextdoorPsycho** [comment]
I need a full log my dude.

**Comment by Armin231** [comment]
@NextdoorPsycho see this https://github.com/VolmitSoftware/Adapt/pull/258
