### ISSUE TITLE
Configurable item for all hunger skills

### ISSUE THREAD

**Issue by doitliketyler** [VolmitSoftware/Adapt#262]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to use a consumable item for some of the hunger skills instead of just using hunger

### What are you trying to modify

I have races setup on my server and one of them is a Vampire that doesn't have to eat because their saturation is permanently full. This race combined with the hunger skills makes the player invincible. A player can literally sit at the bottom of the ocean and infinitely drowned and take damage and never die. I would like a configurable option to make these take away an item from a players inventory versus just taking away from hunger. For example, rotten flesh would be a nice currency for this. A largely pointless item but this would give it some real value and prevent this from happening. Thoughts?

### Alternatives

The only alternative I can think of is either removing the vampire race or remove all skills that take away hunger and both options are not ideal.

**Comment by NextdoorPsycho** [comment]
I added this, I like this idea. Thanks for the suggestion!

**Comment by doitliketyler** [comment]
Amazing. Looking forward to the next update. Cheers
