### ISSUE TITLE
MagicCosmetics Support

### ISSUE THREAD

**Issue by doitliketyler** [VolmitSoftware/Adapt#263]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want cosmetics to not count against skills

### What are you trying to modify

This is my last request...promise (at least for now). I use MagicCosmetics on my server and when a player has any cosmetics equipped it counts against skills that get buffed when not having armor equipped. I know with MagicCosmetics the cosmetic doesn't count as an armor slot so they can have their regular armor and cosmetics equipped but would it be possible to bypass cosmetics being counted as armor for skills? Thanks in advance.

**Comment by NextdoorPsycho** [comment]
im checking the armor a player is wearing, if they have an API that's easy to use, I have no problem adding it, but if its as a pain in the ass as papi ill say no, send me a link to an API

**Comment by doitliketyler** [comment]
Fingers crossed...here you go: https://github.com/FrancoBM12/API-MagicCosmetics/wiki/API

**Comment by NextdoorPsycho** [comment]
Yea this api looks easy to use, unlike papi. Gist tell me what's wrong and ill make the fixes

**Comment by doitliketyler** [comment]
Basically any cosmetic equipped is being recognized as armor by Adapt so it counts against any skills that give buffs for not having armor equipped.

**Comment by NextdoorPsycho** [comment]
Are they Armored?
Like Do the Cosmetics have armor on them?

Ill implement this next update i just need you to tell me what slot these are in because im not trying to install and set this up. if you can tell me what they are, and if they should or should not be counted towards armor  ill add them

Hat
Spray
Bag
Baloon
WalkingStick

**Comment by doitliketyler** [comment]
They shouldn't. Im definitely not doing anything on my side to add armor to them.

Slots:
Hat = Head
Spay = N/A
Bag = Chest
Balloon = N/A
Walking Stick = Offhand

**Comment by NextdoorPsycho** [comment]
Ok!
Ive Added a check to set these Armor Values to 0 whenever im checking for a Helmet or a Bag.

**Comment by doitliketyler** [comment]
What about the offhand slot? That's the main culprit.

**Comment by NextdoorPsycho** [comment]
So, When you are using something like Unarmed Power you are getting a buff as if its a weapon?

**Comment by NextdoorPsycho** [comment]
ok im making it so both hands require AIR
and the Helm/Chest return 0 if its armor

If  its a weapon however i need you to send me a config so i can do testing on my end
