### ISSUE TITLE
It seems I can't edit all the text messages

### ISSUE THREAD

**Issue by xiaozhangup** [VolmitSoftware/Adapt#265]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to Edit all text messages

### What are you trying to modify

No

### Alternatives

plugins... commands...

**Comment by NextdoorPsycho** [comment]
Give me an Example.
Right now the only thing you can't modify is the Advancements, I'll add that when im home. but if its anything else, let me know

**Comment by xiaozhangup** [comment]
> 给我举个例子。现在，您唯一无法修改的是进步，我会在回家时添加它。但如果还有其他问题，请告诉我

Upgrade. Can I ask what time zone you are in?

**Comment by NextdoorPsycho** [comment]
Im un the United States, California, UTC -7 i believe
