### ISSUE TITLE
Console spammed if someone is in worldguard region they don't have access to

### ISSUE THREAD

**Issue by NDTurtle** [VolmitSoftware/Adapt#268]
If someone is in a worldguard region they don't have permissions in, the console will be spammed with the message `[Adapt]: Player tried to use adaptation but they don't have worldguard build permission.`

**Comment by NextdoorPsycho** [comment]
Do you have Verbose on?
What version? That's also experimental. glad its working tho!

**Comment by NextdoorPsycho** [comment]
In the settings you can Toggle the Verbose spam (its only going to get worse) when I fix more issues.

**Comment by NDTurtle** [comment]
Verbose isn't on and it's still spamming. 
![firefox_nVCrYjANP8](https://user-images.githubusercontent.com/65987808/194773328-ffa0f525-462d-420c-8b0b-58a4633ef38e.png)

**Comment by NDTurtle** [comment]
Version is the latest one published to spigot

**Comment by NextdoorPsycho** [comment]
Ok can you try the Hotfix i posted?
