### ISSUE TITLE
java.util.NoSuchElementException issue

### ISSUE THREAD

**Issue by InternetVet** [VolmitSoftware/Adapt#269]
### Problem

Updated to 1.4.3 today, got on after a bike ride and i got this in console after just standing around in game

[15:38:11] [Adapt Workgroup 3/WARN]: java.util.NoSuchElementException
[15:38:11] [Adapt Workgroup 3/WARN]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap$ValuesCollection$1.next(Object2ObjectArrayMap.java:532)

as seen in the log

### Minecraft Version

1.19.2

### Adapt Version

1.4.3

### Log

https://codeshare.io/yoMXp9

**Comment by InternetVet** [comment]
[Githubs.txt](https://github.com/VolmitSoftware/Adapt/files/9740378/Githubs.txt)

Just incase that like isnt working  ^ ^ ^

**Comment by NextdoorPsycho** [comment]
Can you use Purpur or something? Paperclip is strange and they do cut corners for minimal performance gain iirc.
if it still happens on something like spigot or purpur lemme know, either way ill look into it

**Comment by NextdoorPsycho** [comment]
Should be foxed on latest
