### ISSUE TITLE
Fancy / themed Commands

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Adapt#271]
### Adding, Removing, or Changing

Adding

### Type of Modification

Commands section ingame

### What are you trying to modify

Like what iris has but for adapt in a different theme that fits adapt with colors and make them clickable if possible.

### Alternatives

Cry

**Comment by Armin231** [comment]
For the love of god NO! The system iris is using is shitty and also Adapt aims to not be a command skill plugin. The only command there are are just for giving EXP / Knowledge and Debug. It doesn’t need a bloated command system

**Comment by CocoTheOwner** [comment]
Decree is pretty cool tho ngl
The more simple things can be done with it with relatively accurate results

**Comment by Armin231** [comment]
@CocoTheOwner But all the hassle to integrate it for a plugin with 2 debug commands and 2 for giving someone exp or knowledge?

**Comment by CocoTheOwner** [comment]
tru

**Comment by RePixelatedMC** [comment]
> For the love of god NO! The system iris is using is shitty and also Adapt aims to not be a command skill plugin. The only command there are are just for giving EXP / Knowledge and Debug. It doesn’t need a bloated command system

Like themed then like some simple colors to make it feel a bit premium

**Comment by Armin231** [comment]
> > For the love of god NO! The system iris is using is shitty and also Adapt aims to not be a command skill plugin. The only command there are are just for giving EXP / Knowledge and Debug. It doesn’t need a bloated command system
> 
> Like themed then like some simple colors to make it feel a bit premium so no rainbows

Nextdoor will decide if his time is worth that.

**Comment by NextdoorPsycho** [comment]
i mean @CocoTheOwner 
If you want to make the command system use Edict do it, rn im using the OG Mortar command system that birthed Dan's System so i have no idea whats changed

I can probably add that Pizzazz when typing, i just hate documentation/commands lol

**Comment by NextdoorPsycho** [comment]
Im working on this, im using a buddy of mine's command structure now, itll be in a whole new update

**Comment by illyrius666** [comment]
shouldnt this be closed since the commands thing got merged earlier? @NextdoorPsycho
