### ISSUE TITLE
Deconstructing oak planks turns them into birch logs

### ISSUE THREAD

**Issue by NDTurtle** [VolmitSoftware/Adapt#273]
### Problem

1. Get the deconstruction adaption
2. Put an oak plank and shear into a smithing table
3. Observer

### Minecraft Version

1.19.2

### Adapt Version

1.4.3

### Log

https://mclo.gs/rgQwHUQ

**Comment by NextdoorPsycho** [comment]
unable to replicate this, can you send me a video and your playerfile in adapt please?

**Comment by NDTurtle** [comment]
Video: https://streamable.com/v8m882 (please ignore the voice in the background, i was in a vc with my friend)
Data file: https://pastebin.com/6hn1aPK4
