### ISSUE TITLE
Adapt enchantment particles show even when in vanish or spectator

### ISSUE THREAD

**Issue by NDTurtle** [VolmitSoftware/Adapt#275]
### Problem

1. Go near an enchantment table/bookshelf.
2. Go into spectator mode or vanish.
3. Enchantment particles are still visible, even to other players.
Video: https://streamable.com/a9okj6

Please note: I don't know what exactly causes the enchantment particles, it could be something else besides going near an enchantment table.

### Minecraft Version

1.19.2

### Adapt Version

1.4.3

### Log

no log needed

**Comment by NextdoorPsycho** [comment]
So i just tested and it works (i assume you are using Discovery Armor so i made a check for it on dev now, thanks for the report, let me know when i make an update if this fixed it for you as it fixed it for me
