### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to Adapt v1.4.4-1.19.2

### ISSUE THREAD

**Issue by RecanLive** [VolmitSoftware/Adapt#288]
### Problem

...may be damage mobs or etc....

### Solution (if any)

EntityDamageByEntityEvent

### Minecraft Version

1.19.2

### Adapt Version

1.4.4

### Log

https://pastebin.com/gVDg3usm

**Comment by NextdoorPsycho** [comment]
Can you give me a general idea of what you're doing to cause this?

**Comment by RecanLive** [comment]
> Can you give me a general idea of what you're doing to cause this?

Attack monsters or entities

**Comment by InternetVet** [comment]
I aswell have this issue

Log:
 https://codeshare.io/YLKz8M
[latest.log](https://github.com/VolmitSoftware/Adapt/files/9792991/latest.log)

**Comment by NextdoorPsycho** [comment]
@RecanLive @InternetVet does this happen with just adapt? Or is it a plugin thing.

**Comment by NextdoorPsycho** [comment]
Thank you. Fixed
