### ISSUE TITLE
Added Features

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Adapt#29]
These Features are things i want to add at some point to the systems
- [ ] Per World Whitelist / Blacklist
- [ ] Placeholder API
- [ ] Custom Brewing
- [ ] Admin CP Events
- [ ] Add MySql support
- [ ] Boosting xp for a time
- [ ] All of MCMMO's Skills, only the actually good ones, and improve them in every way. [Mining, Woodcutting, Herbalism, Excavation, Fishing, Unarmed]

**Comment by Armin231** [comment]
Add integration with quest plugins like
https://www.spigotmc.org/resources/quests.3711/
https://www.spigotmc.org/resources/questcreator-new-1-19-sqlite-support-and-data-conversion.38734/
https://www.spigotmc.org/resources/betonquest-all-your-adventure-supplies-versatile-quests-in-depth-conversations.2117/

**Comment by Armin231** [comment]
Closing cause this is the proper place https://github.com/orgs/VolmitSoftware/projects/3
