### ISSUE TITLE
Add and write a Wiki

### ISSUE THREAD

**Issue by ArMiN231** [VolmitSoftware/Adapt#3]

**Comment by Raesak** [comment]
Seconded.
There are some plugins that don't have a wiki after 3+ years of updates.
Wiki should be updated with the plugin.

**Comment by CocoTheOwner** [comment]
The plugin is pretty well integrated with vanilla though, so there's not much need for a manual apart from "click a bookshelf" and some commands for admins

**Comment by ArMiN231** [comment]
My idea was more like a todo reminder that there should be a wiki for how to use the config (enable/disable skills, change the required exp and how to add skills)

**Comment by CocoTheOwner** [comment]
Yeah I know. I'll make one real quick

**Comment by CocoTheOwner** [comment]
https://docs.volmit.com/adapt/

**Comment by CocoTheOwner** [comment]
Aaaand the wiki is done, thank thank you, such effort, much completeness

**Comment by CocoTheOwner** [comment]
You may close this now.
