### ISSUE TITLE
Why can't I get experience points by  excavation skills?

### ISSUE THREAD

**Issue by RecanLive** [VolmitSoftware/Adapt#305]
### Problem

You cannot gain experience points in the game..
But attack entities can increase...

### Solution (if any)

I suspect there is something wrong with the code..

axeDamageXPMultiplier It should be axe skill?...

excavation.json
{
    "maxBlastResistanceBonus": 10,
    "axeDamageXPMultiplier": 1,
    "valueXPMultiplier": 0.825,
    "maxHardnessBonus": 90,
    "enabled": true
}

### Minecraft Version

1.19.2

### Adapt Version

1.4.6

### Log

No error output in the log when using the shovel...

**Comment by NextdoorPsycho** [comment]
So if you use any tool as a weapon you should be getting that tool's xp respectively. 
And this might sound like a stupid question but i mean it. Are you able to like just break some dirt with a shovel. and get XP or no? Because i dont see any issues in the code.

**Comment by NextdoorPsycho** [comment]
Cant replicate this issue...
