### ISSUE TITLE
magic foundation glass dupe

### ISSUE THREAD

**Issue by toonystank** [VolmitSoftware/Adapt#308]
### Problem

When using the magic foundation skill if there is an active piston the glass that spawned will move and it does not despawn.

### Minecraft Version

1.19.2

### Adapt Version

1.4.6-1.19.2

### Log

https://mclo.gs/aarZx4C

**Comment by NextdoorPsycho** [comment]
Seen, Fixed on dev

**Comment by NextdoorPsycho** [comment]
https://user-images.githubusercontent.com/29320316/198118120-c915831c-0c39-4e90-9abb-e8b59cc3bdd9.mp4

**Comment by toonystank** [comment]
Thank you for your work :)
