### ISSUE TITLE
When player join server and some other plugin change player's world, Adapt will make some error.

### ISSUE THREAD

**Issue by xiaozhangup** [VolmitSoftware/Adapt#317]
### Problem

1. Install Adapt...
2. Join the server and let some other plugin teleport you.
4. Observe the error...

### Solution (if any)

public void on(PlayerJoinEvent e) {
    Player p = e.getPlayer()
    p.teleport(...);
}

### Minecraft Version

1.19.2

### Adapt Version

1.4.11

### Log

https://mclo.gs/FR6J8m0

**Comment by NextdoorPsycho** [comment]
you dmmed me that this was in fact fixed
