### ISSUE TITLE
Compatible with AdvancedChests

### ISSUE THREAD

**Issue by xiaozhangup** [VolmitSoftware/Adapt#318]
### Adding, Removing, or Changing

Adding

### Type of Modification

make portkey compatible with AdvancedChests

### What are you trying to modify

make portkey can open AdvancedChests's chest.

### Alternatives

SpigotMC Page:https://www.spigotmc.org/resources/%E2%AD%90advancedchests%E2%AD%90-unlimited-sizes-holograms-%E2%9C%A8upgrades-%E2%9C%85sells-%E2%9A%A1sorter-%E2%98%84%EF%B8%8F-compressor.79061/
API:https://github.com/DeadSilenceIV/AdvancedChestsAPI

**Comment by NextdoorPsycho** [comment]
Added on dev branch
