### ISSUE TITLE
Hunters regen needs a condition of having hunger

### ISSUE THREAD

**Issue by TheekshanaA** [VolmitSoftware/Adapt#34]
I spawned a zombie and just let me hit it over and over, and after my hunger has depleted, i was still getting regeneration, making me invincible. A condition to need hunger needs to be added.

**Comment by NextdoorPsycho** [comment]
all hunter skills do

**Comment by NextdoorPsycho** [comment]
They all have it now, and I penalize them with poison if they don't have the hunger (for the duration of the effect)
