### ISSUE TITLE
bossbarNotify

### ISSUE THREAD

**Issue by JamesBach93** [VolmitSoftware/Adapt#348]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to have the Ability to change the actionbarNotify to bossbarNotify.

### What are you trying to modify

Only an way to use actionbarNotify or bossbarNotify.
Thats because im Using "Oraxen" for Custom Items (Texturepack).
And im using from this the ability to modify the Hud. And this is on the actionbar this means it shows really quickly the Information.

### Alternatives

No Alternatives

**Comment by NextdoorPsycho** [comment]
what information do you want?
The xp gain like when you get discovery or experience, or the HUD notifications like LEVEL 33?

**Comment by NextdoorPsycho** [comment]
no reply, Closing
