### ISSUE TITLE
Some bugs and some suggestions for enhancement 

### ISSUE THREAD

**Issue by TheekshanaA** [VolmitSoftware/Adapt#35]
**Bugs:**
- Herbalist -  growth aura (Doesn’t do anything?)
- Agility - armour up (crashed server, no just doesn’t do anything)
- Axe - axe chop (just doesn’t work)
- Excavation - hast excavator (blocks break then re-appear, very laggy, leads to ghost blocks)
- Nether - Wither skull throw (after 1 throw, no longer works)

**Suggested Changes:**
- Button to unequip all skill points (barrier block)
- Back button in GUI’s (bed top right of GUI’s)
- Escape leaves the skill menu entirely, instead of re-entering 
- Command to open GUI (/skill and /skills)
- Hover mouse over each category, to see how much power that category is currently using

**Comment by NextdoorPsycho** [comment]
1: herbalism, it dies work. You need to be in survival and have saturation

**Comment by NextdoorPsycho** [comment]
2: crash, only you. Still haven't gotten a report from what plugin is causing it from your end

**Comment by NextdoorPsycho** [comment]
3: chop, right click a tree an axe lol

**Comment by NextdoorPsycho** [comment]
4: excavation, slow server. I'm just applying haste so if your server is unable to handle hate is the equivalent of a beacon of hate

**Comment by NextdoorPsycho** [comment]
5: nether, the should be a cooldown. Can you elaborate

**Comment by NextdoorPsycho** [comment]
Button, maybe but no. Had plans to add more skills. Be aware of what you get

**Comment by NextdoorPsycho** [comment]
Back button, literally hit escape

**Comment by NextdoorPsycho** [comment]
Esc leaves. Ya that's the point

**Comment by NextdoorPsycho** [comment]
Command, sure

**Comment by NextdoorPsycho** [comment]
Hover, idk maybe

**Comment by TheekshanaA** [comment]
> Back button, literally hit escape

We need a back button because currently when u click escape it closes and reopens GUI and it's very laggy.


> Button, maybe but no. Had plans to add more skills. Be aware of what you get

Maybe you can do it via a command

> Hover, idk maybe

Once you have a lot of skills equipped it gets very confusing and overwhelming so it would be useful.

**Comment by Armin231** [comment]
Adapt wont feature any commands. It was designed that it wont ever need any commands

**Comment by TheekshanaA** [comment]
> Adapt wont feature any commands. It was designed that it wont ever need any commands

It won't actually change anything for adapt other than a QOL for people that want to use a command other than a bookshelf.
