### ISSUE TITLE
Magic foundation drop glass if you explode it

### ISSUE THREAD

**Issue by abola2** [VolmitSoftware/Adapt#354]
### Problem

If I explode using creeper or tnt magic foundation tinted glass it drop that glass.

(version 1.19.3 paper)

### Solution (if any)

-

### Minecraft Version

1.19.2

### Adapt Version

1.4.22

### Log

no error or anything on console when this happen

**Comment by NextdoorPsycho** [comment]
Thank you for reporting

**Comment by NextdoorPsycho** [comment]
Fixed on dev
