### ISSUE TITLE
NullPointerException Console Spam [I DON'T KNOW WHAT A LOG IS]

### ISSUE THREAD

**Issue by VerfiyNull** [VolmitSoftware/Adapt#355]
### Problem

1. Install Adapt...
2. Restart the Server

Spigot 1.19

### Minecraft Version

1.19.2

### Adapt Version

1.4.22

### Log

https://hastebin.com/afehiyabuh.yaml

**Comment by VerfiyNull** [comment]
Figured I would add to the ticket with another similar issue.
Same Server, but this 'Null player' happens even when a player is online.
please check for null objects :/
https://hastebin.com/azabicowiq.yaml

**Comment by NextdoorPsycho** [comment]
Thank you I'll look into it

**Comment by NextdoorPsycho** [comment]
Neither of these are full logs. so im not even going to attempt to look into it.

**Comment by NextdoorPsycho** [comment]
None of your logs go anywhere, and this is inactive. 
if its so easy to just "check for null objects" which is such an ignorant vague comment with out knowing the source and are unable to send me a full log, I don't have the interest in helping resolve this. please provide me with anything in a new issue. Thank you
![CleanShot 2022-12-29 at 12 38 15@2x](https://user-images.githubusercontent.com/29320316/210008892-7b557adc-4525-4f8c-a619-8ea77b11e834.png)
