### ISSUE TITLE
ERROR [I DON'T KNOW WHAT A LOG IS]

### ISSUE THREAD

**Issue by wkurumi** [VolmitSoftware/Adapt#356]
### Problem

1. Install Adapt...
2. Do this...
3. Do that...
4. Observe the error...
I don't know anything.It may be incompatible with EliteMobs or EcoEnchants，Plugins List：
Adapt, AuthMe, AuthmeExpansion, BetterStructures, Citizens, CMI, CMIEInjector*, CMILib, CoreProtect, CratesLottery, CustomCrops, DeluxeMenus, EasyGuiShop, eco, EcoEnchants, EliteMobs, FastAsyncWorldEdit (WorldEdit), GDHooks, GriefDefender, ItemsAdder, LibsDisguises, LinearBot, LoneLibs, LuckPerms, MiniMOTD, MiraiMC, Multiverse-Core, NBTAPI, OpenInv, PlaceholderAPI, PlayerPoints, PlayerTitle, ProtocolLib, QuickShop-Hikari, RealisticSeasons, RhyPay*, Shopkeepers, SkinsRestorer, UltimateTimber, Vault, WkKit, WorldGuard, WorldGuardExtraFlags, YukiNoaAPI

### Solution (if any)

It may be incompatible with EliteMobs or EcoEnchants.

### Minecraft Version

1.19.2

### Adapt Version

1.4.20

### Log

https://pastebin.com/UG79fREg

**Comment by NextdoorPsycho** [comment]
Not a Full log.

**Comment by wkurumi** [comment]
1
