### ISSUE TITLE
Bug de duplication bûche d'arbre

### ISSUE THREAD

**Issue by NeptunaMH** [VolmitSoftware/Adapt#359]
1. Apprendre les skills Axe Vein Miner + axe drop in inventory
2. Poser quelques bûches de bois (minimum 2)
3.  Casser une bûche avec le skill Axe Vein Miner 
4.  Vous récupérerez  le doubles des bûches placé moins 1

Le bug ne marche pas sans le skill Axe Drop In Inventory

**Comment by NextdoorPsycho** [comment]
Corrigé, merci l'ami !
