### ISSUE TITLE
Bug Axe Vein Miner "reach" illimité 

### ISSUE THREAD

**Issue by NeptunaMH** [VolmitSoftware/Adapt#360]
Contexte : Axe Vein Miner niveau maximum peut casser dans un périmètre de 8 blocs

1. Apprendre les skill Axe Vein Miner + axe drop in inventory
2. Avec les deux skill vous pouvez casser dans un périmètre quasi illimité temps que les deux arbres sont assez proches

Ne marche pas sans Axe drop in inventory

**Comment by NextdoorPsycho** [comment]
Cela devrait également être corrigé. Merci
