### ISSUE TITLE
Griefprevention support

### ISSUE THREAD

**Issue by abola2** [VolmitSoftware/Adapt#362]
### Problem

If you mine outside griefprevention claim using veinminer it's mines ores inside claim... Same problem is also with tree chopping / leaf mining

### Solution (if any)

Skills should check if player have permission break blocks

### Minecraft Version

1.19.2

### Adapt Version

Adapt-1.4.23-1.19.3

### Log

-

**Comment by NextdoorPsycho** [comment]
Send me a link

**Comment by abola2** [comment]
https://www.dropbox.com/s/91er4xcz8mc0hvr/javaw_Djuh7mRXkf.mp4?dl=0

>

**Comment by NextdoorPsycho** [comment]
no, they have zero documentation. and don't intend to add it anytime soon.
https://docs.griefprevention.com/api/
Feel free to PR it in if you want to add it, otherwise this is going on the back burner
