### ISSUE TITLE
Spamming rod air gives free Ranged Xp

### ISSUE THREAD

**Issue by abola2** [VolmitSoftware/Adapt#363]
### Problem

![image](https://user-images.githubusercontent.com/81980535/209720214-d3820681-bdd7-41d9-854b-07d3f4ace5e0.png)

If you spam rod on air it gives free ranged xp

(Spamming rod on air doesn't use rod durability)

### Minecraft Version

1.19.2

### Adapt Version

Adapt-1.4.23-1.19.3

### Log

-

**Comment by NextdoorPsycho** [comment]
I thought it used durability, my bad! ill fix this rn
