### ISSUE TITLE
PICKAXE Entity bug

### ISSUE THREAD

**Issue by abola2** [VolmitSoftware/Adapt#364]
### Problem

Is there some reason why hitting entity using pickaxe gives mining xp? It's feel wrong that you kill mob grinder mobs using pickaxe and you get mining xp. Also hitting armor stand using pickaxe gives mining xp

![image](https://user-images.githubusercontent.com/81980535/209723258-a6d53a21-7126-467f-9e93-e2c2eb613994.png)

### Solution (if any)

-

### Minecraft Version

1.19.2

### Adapt Version

Adapt-1.4.23-1.19.3

### Log

-

**Comment by NextdoorPsycho** [comment]
Fixed entity Detection, should fix this
