### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by HeartlessAUS** [VolmitSoftware/Adapt#367]
### Adding, Removing, or Changing

Adding

### Type of Modification

For use outside of predefined block

### Commands
An extension of the commands would be great for using Adapt via other plugins. Simple implementations of commands such as the following:

1. /adapt open gui [catagory]
- Opens the defined catagory
- Example: (/adapt open gui agility) would open the agility skills catagory
- Alternative command could be: /adapt [catagory]

2. /adapt open gui [catagory] [skill]
- Opens the defined skill
- Example: (/adapt open gui agility windup) would open the wind up skill in agility
- Alternative command could be: /adapt [skill]
- Can be given a few different names for ease of users (example: "wind up" could have windup, wind-up and wind up)

**Comment by NextdoorPsycho** [comment]
I think I enhanced the current system to be able to do it!
ill need to text it and im on an airplane at the time of writing this message. 
but for now the implementation is done I believe, ill text and merge it when I can!
