### ISSUE TITLE
Cant load the plugin![i don't know what a log is]

### ISSUE THREAD

**Issue by TheSheepy** [VolmitSoftware/Adapt#368]
### Problem

1. Install Adapt...
2. then i start the server
3. plenty of error happenned

### Solution (if any)

maybe the plugin not support paper1.19.3

### Minecraft Version

1.19.2

### Adapt Version

Adapt-1.5.0-1.19.3

### Log

https://mclo.gs/4RgzB7i

**Comment by TheSheepy** [comment]
sry,i have a 1.19.3 server and use the latest version



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月6日(星期五) 晚上6:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VolmitSoftware/Adapt] Cant load the plugin! (Issue #368)





 
So you have a 1.19.2 server with 1.19.3 jar? Like the jar says 1.19.3 not 1.19.2

**Comment by NextdoorPsycho** [comment]
send a full log or you're not getting any help

**Comment by RePixelatedMC** [comment]
Go to the volmit discord server we can assist you further there
