### ISSUE TITLE
Rift Gate not consume

### ISSUE THREAD

**Issue by zinezockt** [VolmitSoftware/Adapt#374]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want that the Rift Gate doesnt get consumed

### What are you trying to modify

I want an option to toggle that the EyeAnchor isnt consumed while teleporting (like a home point).

### Alternatives

I would implement this is by having a true/false option in rift.json ("anchorConsumeOnUse": false).
Default false ofc, and if true you its not getting consumed

**Comment by NextdoorPsycho** [comment]
Added:
https://gist.github.com/4aa4d50f57e0892d3e6edf3d500dcfaf
Will be in next Version
