### ISSUE TITLE
"remote access" bypass residence

### ISSUE THREAD

**Issue by FallenCrystal** [VolmitSoftware/Adapt#377]
### Problem

1. learn "remote access" skills
2. create skill items
3. bind the container
4. keep away from containers
5. use skill items to open containers. u'll bypass residence protect and is not logged by residence.

### Solution (if any)

obey the permissions of the residence. and the behavior of manipulating the container is recorded normally by residence.
btw why is the mc version i can choose is 1.19.2? what about 1.2, 1.21 and 1.22? i indicated at the version that im using 1.19.3.

### Minecraft Version

1.19.2

### Adapt Version

1.5.0 (NMS1.19.3) Build (commit:c2133fc2af222cf58d46fe0c9b4b41ba71b65cb1)

### Log

no any logs

**Comment by AkariDream** [comment]
my fault. it can be logged by coreprotect. but still bypass residence

**Comment by AkariDream** [comment]
![Spigot Link](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-19.11480/)
![Github](https://github.com/Zrips/Residence)

**Comment by IPECTER** [comment]
@NextdoorPsycho
Can you add BlockProt Support?
https://github.com/spnda/BlockProt

**Comment by AkariDream** [comment]
> `@NextdoorPsycho` Can you add BlockProt Support? https://github.com/spnda/BlockProt

i think he should be busy. however this looks like this should open a new issue. :\
`opened this issue on Jan 16`

**Comment by NextdoorPsycho** [comment]
I've seen this. I just forgot to add it.

**Comment by NextdoorPsycho** [comment]
resolved
