### ISSUE TITLE
"Adapt Block" translation issue

### ISSUE THREAD

**Issue by poikcue** [VolmitSoftware/Adapt#378]
### Problem

Located in file src/main/resources/en_US.json (key `snippets.gui.unlockthisbyclicking`).

Players may not be aware of what block "Adapt Block" refers to, so they may not be able to open the correct GUI.

It is recommended that a key be added to the configuration file to allow server administrators to change this "Adapt Block" to what they want to set.

### Discord Username

poikcue#5870

### Adapt Version

1.5.1

**Comment by NextdoorPsycho** [comment]
Fixed, will make update
