### ISSUE TITLE
The server keeps reporting errors after Adapt plugin is loaded

### ISSUE THREAD

**Issue by Syscat20** [VolmitSoftware/Adapt#379]
### Problem

I purchased this plugin on SpigotMC. I have installed the Geyser plugin and the floodgate plugin on my server to allow players of the bedrock version to play on the server as well. However, once the plugin is loaded, the Adapt plugin keeps reporting errors as soon as the bedrock player joins the game. Even if the player exits the game, the Adapt plugin will continue to report errors.
1. Install Adapt...
2. Player join...
3. Observe the error...

### Solution (if any)

I think it may be that the events handled by the plugin are not being passed to the bedrock version. Hopefully this issue will be fixed.

### Minecraft Version

1.19.2

### Adapt Version

1.5.1-1.19.3

### Log

https://mclo.gs/y4jdmsN

**Comment by NextdoorPsycho** [comment]
you literally solved the issue in your report...

https://i.imgur.com/tEbBEEt.png

you either need an older Adapt version or a newer server version
