### ISSUE TITLE
Some suggestion about translation

### ISSUE THREAD

**Issue by poikcue** [VolmitSoftware/Adapt#388]
### Problem

1. The key `snippets.adaptmenu.knowledgecost` will be used twice. The first place is below skill name description, and the second place is "You only have %num% Knowledge Cost". I would suggest splitting this message into different keys, using `snippets.adaptmenu.knowledgecost` in the first place (below skill name description) and `snippets.adaptmenu.knowledgeavailable` in the second place ("You only have %num% Knowledge Cost").
```
...
    "adaptmenu": {
      "maynotunlearn": "YOU MAY NOT UNLEARN",
      "mayunlearn": "YOU MAY LEARN/UNLEARN",
      "knowledgecost": "Knowledge Cost",
      "knowledgeavailable": "Knowledge available",  <-- NEW KEY
      "alreadylearned": "Already Learned",
...
```

2. Can "adaptActivatorBlock" use client-side localization? Or add a command within the game to allow the admin to set localised display text. Some players who don't speak English may have trouble when they try to understand the meaning of word, doing so can help improve their experience.

3. Can Adapt add a command-based language switching system? (e.g.  `/adapt lang en_US` )

### Discord Username

poikcue#5870

### Adapt Version

 1.5.3

### Screenshot

No screenshot.

**Comment by NextdoorPsycho** [comment]
knowledgecost / knowledgeavailable added
adaptActivatorBlock now has its own translatable key in the lang file
ill keep the command on the backburner for now, expect these changes and some reworks in the next update
