### ISSUE TITLE
Agility hotloading causes outofbuond exception error

### ISSUE THREAD

**Issue by mrfloris** [VolmitSoftware/Adapt#399]
### Problem

Freshly installed adapt last week, and opened the agiliy json file it generated. For then, I set enabled to false, and run the plugin fine .. now we're ready to unlock agility and I set it to true, and noticed it hotloads the plugin json file and spits out an exception error

paper 1.19.3 build 431

<img width="761" alt="Screen-Shot 2023-03-04 at 09 21 56" src="https://user-images.githubusercontent.com/28841349/222885428-0a809f7f-315f-428a-ad07-674ba302ce92.png">

```json
{
    "sprintXpPassive": 1.25,
    "challengeSprintMarathonReward": 6500,
    "challengeMove1kReward": 500,
    "enabled": true,
    "challengeSprint5kReward": 2000
}
```
after first install, changed true to false, and now after a week I changed it back to true and clicked save. i didn't change any other values. 

### Solution (if any)

no idea.

### Minecraft Version

1.19.2

### Adapt Version

1.6.1-1.19.3

### Log

https://paste.md-5.net/ipezopasum.cs

**Comment by NextdoorPsycho** [comment]
Send a full log, Adapt is version independent. update your server. 
then try again tell me if its borked

**Comment by mrfloris** [comment]
1.19.3 is what we run, we're on build 431 - the form to file an issue is limited to 1.19.2 Just an FYI. Will double check spigot for new adapt build and paper's site for new build version, and see if I can reproduce the issue. Thank you for replying.
