### ISSUE TITLE
[Adapt]: Failed to send collected packet

### ISSUE THREAD

**Issue by OtakuSweett** [VolmitSoftware/Adapt#400]
### Problem

On some occasions the plugin starts spamming me messages in the console about not being able to collect the package. I have tried to block them because I haven't seen that they affect anything but they still end up coming out since they change, I wanted to see how to fix this

### Minecraft Version

1.19.2

### Adapt Version

1.6.1-1.19.3

### Log

https://pastebin.com/VGHu5mBj

**Comment by RePixelatedMC** [comment]
Adapt version 1.19.3 
Server version 1.19.2

**Comment by NextdoorPsycho** [comment]
update your server / downgrade adapt
version of adapt clearly says on the jar 1.19.3

**Comment by OtakuSweett** [comment]
I made a mistake when putting the version of my server I am using 1.19.3
![image](https://user-images.githubusercontent.com/85897417/222996852-8fac0178-2a7e-4272-8565-72a0cbe8852e.png)

**Comment by NextdoorPsycho** [comment]
can you send a full log please. 
And what are they trying to pick up? 
if you are able to replicate it 100% of the time lemme know and i can easily fix it

**Comment by OtakuSweett** [comment]
Hello, I've been researching what the cause is, and I've found 1 of the many problems that occur with "packets" I'll continue investigating the others that sometimes spam the console, well I'll get to the point, One is with the "Stealth Snatch" skillYou can see it in the video that I will attach at the end, regardless of whether you have a full or empty inventory, throwing an object at a mob that is attacking you from a distance , sends the packet message

[Video](https://cdn.discordapp.com/attachments/1037785903868952606/1082363959757250671/2023-03-06_12-04-16.mp4)

[Log](https://pastebin.com/9pWnu35p)

**Comment by NextdoorPsycho** [comment]
try latest
