### ISSUE TITLE
Shulker's Nightmare

### ISSUE THREAD

**Issue by MineForce899** [VolmitSoftware/Adapt#404]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to add ability

### What are you trying to modify

The way I would implement this is:
If player has levitation effect and he is sneaking => levitation effect is removed and slow falling effect is applied to player
https://gifyu.com/image/S7XE4 << example, made with skript

### Alternatives

plugins... (skript?) commands... (/effect?)

**Comment by NextdoorPsycho** [comment]
sure!

**Comment by NextdoorPsycho** [comment]
Added!
