### ISSUE TITLE
Poison Blade Not Respecting PvP Rules in Regions and WorldGuard Flags

### ISSUE THREAD

**Issue by apollonmeddev** [VolmitSoftware/Adapt#407]
### Problem

The Poison Blade adaptation in the Adapt plugin is not respecting PvP rules in regions and WorldGuard flags. Even if PvP is disallowed in a specific region by a WorldGuard flag, the Poison Blade can still damage players or mobs, which is not consistent with the intended behavior. This can lead to unintended consequences such as players being killed in regions where PvP is not allowed, which can negatively impact the gameplay experience.

To reproduce this issue, I have set up a server with the Adapt plugin and configured several regions using WorldGuard to disallow PvP. I then tested the Poison Blade adaptation in these regions and found that it can still damage players and mobs. This is inconsistent with the expected behavior, and the Poison Blade should respect the PvP rules and WorldGuard flags set on the server.

### Minecraft Version

1.19.2

### Adapt Version

Adapt-1.4.20-1.19.2

### Log

nothing to show

**Comment by NextdoorPsycho** [comment]
resolved
