### ISSUE TITLE
/adapt give command for random xp orb 

### ISSUE THREAD

**Issue by datarat010** [VolmitSoftware/Adapt#408]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to be able to add random orbs of knowledge or xp to voting reward chests if possible

### What are you trying to modify

The way I would implement this is give my self the xp or knowledge orb that is a random one until using orb, then put item in reward chests for my players. If this is already doable i apologize profusely, i checked the discord and command list before posting .

### Alternatives

plugins... commands...

**Comment by NextdoorPsycho** [comment]
Ive added this, Expect it in a future update 1.8.1 probably
