### ISSUE TITLE
Harvest & Replant interfers with Hoe Drop-To-Inventory

### ISSUE THREAD

**Issue by Armin231** [VolmitSoftware/Adapt#41]
Basically what the titel says

**Comment by NextdoorPsycho** [comment]
can you explain what is happening lol
any dupes?

**Comment by Armin231** [comment]
> can you explain what is happening lol
> any dupes?

If I remember correctly if you use harvest & replant the drops won’t get teleported to your location

**Comment by Armin231** [comment]
Okay, the Harvest & Replant has a radius depending on the Level of it. Hoe Drop-To-Inventory is only working for the block you click not the blocks its surrounded. Therefore you'll pick up the drops of the block faced and the rest will be dropped to the ground

**Comment by NextdoorPsycho** [comment]
Fixed
