### ISSUE TITLE
An API to cancel certain skills of our choice

### ISSUE THREAD

**Issue by MisterEpic** [VolmitSoftware/Adapt#414]
### Adding, Removing, or Changing

Adding

### Type of Modification

Have an API to cancel certain skills of our choice for our factions plugin

### What are you trying to modify

The skill we primarily want this for is rift blink. Currently, players can use rift blink to blink into the bases of other factions in our factions gamemode. Obviously we cant have this, but would like to keep the skill, so were wondering if we could have the API to disable such a skill in factions claims.

### Alternatives

Disbabling it is the only alternative unfortunately.

**Comment by NextdoorPsycho** [comment]
Include adapt the plugin in your compile script. I assume as a developer somewhere you are able to do this.
```
    public void on(AdaptAdaptationUseEvent e) {
    // your code here
    }
```

You can also blacklist permissions:
Give someone these permission nodes to blacklist any skill in specific:
adapt.blacklist.tragoulthorns
adapt.blacklist.tragoulglobe
adapt.blacklist.tragoulhealing
adapt.blacklist.tragoullance
adapt.blacklist.enchantingquickenchant
adapt.blacklist.enchantinglapisreturn
adapt.blacklist.enchantingxpreturn
adapt.blacklist.netherwitherresist
adapt.blacklist.netherskulltoss
adapt.blacklist.herbalismgrowthaura
adapt.blacklist.herbalismreplant
adapt.blacklist.herbalismhungryshield
adapt.blacklist.herbalismhippo
adapt.blacklist.herbalismdroptoinventory
adapt.blacklist.herbalismluck
adapt.blacklist.herbalismmyconid
adapt.blacklist.herbalismterralid
adapt.blacklist.herbalismcobweb
adapt.blacklist.herbalismcobweb
adapt.blacklist.pickaxechisel
adapt.blacklist.pickaxeveinminer
adapt.blacklist.pickaxeautosmelt
adapt.blacklist.pickaxedroptoinventory
adapt.blacklist.architectglass
adapt.blacklist.architectfoundation
adapt.blacklist.architectplacement
adapt.blacklist.architectwirelessredstone
adapt.blacklist.axegroundsmash
adapt.blacklist.axechop
adapt.blacklist.axedroptoinventory
adapt.blacklist.axeleafveinminer
adapt.blacklist.axewoodveinminer
adapt.blacklist.axelogswap
adapt.blacklist.swordmachete
adapt.blacklist.swordpoisonblade
adapt.blacklist.swordbloodyblade
adapt.blacklist.riftresist
adapt.blacklist.riftaccess
adapt.blacklist.riftenderchest
adapt.blacklist.riftgate
adapt.blacklist.riftblink
adapt.blacklist.riftdescent
adapt.blacklist.brewinglingering
adapt.blacklist.brewingsuperheated
adapt.blacklist.brewingabsorption
adapt.blacklist.brewingblindness
adapt.blacklist.brewingdarkness
adapt.blacklist.brewingdecay
adapt.blacklist.brewingfatigue
adapt.blacklist.brewinghaste
adapt.blacklist.brewinghealthboost
adapt.blacklist.brewinghunger
adapt.blacklist.brewingnausea
adapt.blacklist.brewingresistance
adapt.blacklist.brewingsaturation
adapt.blacklist.rangedforce
adapt.blacklist.rangedpiercing
adapt.blacklist.rangedrecovery
adapt.blacklist.rangedlungeshot
adapt.blacklist.rangedwebshot
adapt.blacklist.blockingmultiarmor
adapt.blacklist.blockingchainarmorer
adapt.blacklist.blockingsaddlecrafter
adapt.blacklist.blockinghorsearmorer
adapt.blacklist.craftingdeconstruction
adapt.blacklist.craftingxp
adapt.blacklist.craftingleather
adapt.blacklist.craftingskulls
adapt.blacklist.craftingbackpacks
adapt.blacklist.craftingstations
adapt.blacklist.craftingreconstruction
adapt.blacklist.discoveryunity
adapt.blacklist.discoveryworldarmor
adapt.blacklist.discoveryxpresist
adapt.blacklist.discoveryvillageratt
adapt.blacklist.seaborneoxygen
adapt.blacklist.seabornespeed
adapt.blacklist.seabornefishersfantasy
adapt.blacklist.seaborneturtlesvision
adapt.blacklist.seaborneturtlesminingspeed
adapt.blacklist.excavationhaste
adapt.blacklist.excavationspelunker
adapt.blacklist.excavationomnitool
adapt.blacklist.excavationdroptoinventory
adapt.blacklist.stealthspeed
adapt.blacklist.stealthsnatch
adapt.blacklist.stealthghostarmor
adapt.blacklist.stealthvision
adapt.blacklist.unarmedsuckerpunch
adapt.blacklist.unarmedpower
adapt.blacklist.unarmedglasscannon
adapt.blacklist.agilitywindup
adapt.blacklist.agilitywalljump
adapt.blacklist.agilitysuperjump
adapt.blacklist.agilityarmorup
adapt.blacklist.hunteradrenaline
adapt.blacklist.hunterregen
adapt.blacklist.hunterinvis
adapt.blacklist.hunterjumpboost
adapt.blacklist.hunterluck
adapt.blacklist.hunterspeed
adapt.blacklist.hunterstrength
adapt.blacklist.hunterresistance
adapt.blacklist.hunterdroptoinventory
adapt.blacklist.tamehealth
adapt.blacklist.tamedamage
adapt.blacklist.tamehealthregeneration
