### ISSUE TITLE
Important Quality of Life Changes, with explanations of their importance.

### ISSUE THREAD

**Issue by MisterEpic** [VolmitSoftware/Adapt#42]
I believe that the plugin is really well done, but I feel there are some issues which when put in practice, will prove quite unenjoyable for players.

1. Back button in GUI
Currently, clicking escape to go back closes and reopens the GUI briefly, which gets annoying fast. A button, such as a bed or other item which allows players to go back without the GUI quickly opening and closing would be great. My rationale behind this feature, is that once players become familiar with the plugin and skills, they likely will want to learn/unlearn skills quickly, and the delay between going back to each GUI will likely become quite frustrating.

![bed1](https://user-images.githubusercontent.com/111988642/186429414-2c86e0ce-4057-43e5-b6c7-70457d8b4cc8.png)
![bed2](https://user-images.githubusercontent.com/111988642/186429433-52d758e7-479c-4caf-b70c-6fba65f80529.png)

2. Escape key leaves entire GUI immediately
In conjuction with the first suggestion, making the escape key leave the entire GUI, even when in specific skill trees/abilities would also make use of the plugin more enjoyable. Players with higher ping will find this delay in leaving the GUI even more annoying. This delay may also prove problematic when in scenarios such as factions, where your base is being raided and you quickly need to change skills.
Players who also become very familiar with the skills/abilities, may also get frustrated when quickly switching/equipping skills, and being unable to leave the GUI immediately.

![escapegif2](https://user-images.githubusercontent.com/111988642/186431186-29a141fd-7f10-4010-a128-eca38f88cdcf.gif)

3. GUI remains open when learning a skill
Currently when selecting a skill (as demonstrated in the above gif), the GUI closes and reopens.
I won't go into detail on why this should be added, as the logic follows what i've already written in suggestion 1 and 2. If the GUI remained open upon selecting skills, I believe that would be a great addition.

4. Button to unequip/unlearn all skills
Once players enter the higher levels, keeping track of all the skill trees their power is invested in can get tough. I believe a button in the GUI like a barrier block, which when clicked unlearns all skills at once will greatly help this. Understandably, more abilities will be added in the future, and this will take up a GUI slot, so maybe a command could be used instead (e.g. /respec), or the GUI could be expanded into a double chest? 
Simply put, I believe such a feature is important due to players potentially having multiple "builds". For example, players may choose to learn more hunter abilities/axe abilities when in combat, but prefer architect abilities/excavation abilities in base construction. Having an easy method of unlearning all abilities, instead of requiring players to manually go through and select each skill to unlearn, would be incredibly useful.

![barrierblock](https://user-images.githubusercontent.com/111988642/186432564-fbabc64f-0748-4cf9-8e72-6759f02023fe.png)

~~5. Hovering mouse over categories, to see how much power that category is using.
This follows the same rationale as suggestion 4, whereby keeping track of all abilities learn't can become difficult and tedious when at higher levels. The image below provides 2 examples of how this could look.
I believe this suggestion will also be very useful for newer players, who still aren't as comfortable with the mechanics of the plugin (such as power, knowledge, etc), making it easier for them to understand whats going on, and learn how power functions.~~
(EDITED BY NEXTDOOR PSYCHO, ADDED THIS FEATURE)

![power](https://user-images.githubusercontent.com/111988642/186433430-e2021907-6f35-461a-9907-5d8ecda05279.png)

~~6. A command to open the GUI (/skill or /skills)
Fairly self-explanatory, but this is just a quality of life change I believe will only further the plugin. I think the bookshelf idea is super cool, but may prove slightly annoying in practice. Newer players without access to a bookshelf will be unable to easily view their skills, and players on the move or out in the wilderness may also find it annoying to have to place a bookshelf everytime they want to open the GUI. Furthermore, for gamemodes such as factions and survival where you cannot place blocks in certain claimed land, a command to open the GUI would prove very useful.~~
(EDITED BY NEXTDOOR PSYCHO, ADDED THIS FEATURE)

Apologies for the longer post, I believe this plugin is super awesome and has so much future potential, and all these quality of life changes should only further make that so!

**Comment by NextdoorPsycho** [comment]
[1, 2, 3]: if I add a back button the same thing is going to happen, that's how im managing GUI's I think that your server might have a slow FileService, but I can look into speeding that up, if rather keep it esc, as that does not seem to be an issue, but the issue arises with the GUI being Sluggish, that I can Fix I believe. and it would be a good compromise. this would, in turn also make the other issues go away.

**Comment by NextdoorPsycho** [comment]
4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)

**Comment by NextdoorPsycho** [comment]
> > [1, 2, 3]: if I add a back button the same thing is going to happen, that's how im managing GUI's I think that your server might have a slow FileService, but I can look into speeding that up, if rather keep it esc, as that does not seem to be an issue, but the issue arises with the GUI being Sluggish, that I can Fix I believe. and it would be a good compromise. this would, in turn also make the other issues go away.
> 
> Regarding this, it definitely can't be our file service as we run on a raid 0 m.2 ssd storage. Giving us 3.32GBps of drive speed. We run other plugins through the files and it has no issues. If you'd like add SQL support we can accommodate using that if it means the GUI issues will be fixed.

I mean, im on a shitty Mac in power save mode and I have no issues lol

**Comment by Armin231** [comment]
Guys Adapt is open source (the way you already got the plugin). Utilize the open source feature and create PRs for adapt

**Comment by NextdoorPsycho** [comment]
oops did not mean to close

**Comment by MisterEpic** [comment]
> [1, 2, 3]: if I add a back button the same thing is going to happen, that's how im managing GUI's I think that your server might have a slow FileService, but I can look into speeding that up, if rather keep it esc, as that does not seem to be an issue, but the issue arises with the GUI being Sluggish, that I can Fix I believe. and it would be a good compromise. this would, in turn also make the other issues go away.

That would be ok, but its still annoying to not be able to immediately leave the GUI upon selecting a skill tree for example.

**Comment by TheekshanaA** [comment]
> > > [1, 2, 3]: if I add a back button the same thing is going to happen, that's how im managing GUI's I think that your server might have a slow FileService, but I can look into speeding that up, if rather keep it esc, as that does not seem to be an issue, but the issue arises with the GUI being Sluggish, that I can Fix I believe. and it would be a good compromise. this would, in turn also make the other issues go away.
> > 
> > 
> > Regarding this, it definitely can't be our file service as we run on a raid 0 m.2 ssd storage. Giving us 3.32GBps of drive speed. We run other plugins through the files and it has no issues. If you'd like add SQL support we can accommodate using that if it means the GUI issues will be fixed.
> 
> I mean, im on a shitty Mac in power save mode and I have no issues lol Nowhere as well, no issues, and he's on German ™️ internet

Yeah well I can't comment on why it's happening other than maybe an issue in the code because our other plugins running on the same drive and specs have zero issues using files as a DB.

**Comment by NextdoorPsycho** [comment]
and for the power thing I can look into that, I just hate how that part works and its buggy if I fuck with it

**Comment by NextdoorPsycho** [comment]
and I thing its a you problem, as your server also crashed when players get armor lolol. let me know what plugin that is and I can see about fixing that, and that's probably the issue for this too

**Comment by MisterEpic** [comment]
> 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)

I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.

**Comment by NextdoorPsycho** [comment]
> > 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)
> 
> I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.

you literally can't have enough skills for it to be tedious, I made it in such a way that you can only have like 5 maxed skills, or like 15 level 1 skills (which is a waste for everything)

**Comment by TheekshanaA** [comment]
> and I thing its a you problem, as your server also crashed when players get armor lolol. let me know what plugin that is and I can see about fixing that, and that's probably the issue for this too

We run the server via Pterodactyl if that means anything but that shouldn't really be causing any issues as every plugin works through there. It's definitely something in your code base.

**Comment by MisterEpic** [comment]
> > > 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)
> > 
> > 
> > I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.
> 
> you literally can't have enough skills for it to be tedious, I made it in such a way that you can only have like 5 maxed skills, or like 15 level 1 skills (which is a waste for everything)

Even with only 5 skills, having the ability to reduce clicks by 10-20 (entering each skill tree and unlearning them) would greatly reduce its tedious nature. Especially if players are regularly respecing

**Comment by NextdoorPsycho** [comment]
> > and I thing its a you problem, as your server also crashed when players get armor lolol. let me know what plugin that is and I can see about fixing that, and that's probably the issue for this too
> 
> We run the server via Pterodactyl if that means anything but that shouldn't really be causing any issues as every plugin works through there. It's definitely something in your code base.

again, im not saying your server is bad. im saying there is a plugin incompatibility, as im running this on a lowpowermac, and playing and having no issues, we also use akliz for our server, and no issues, and nowhere is German ™️  with no issues, im 100% certain its a plugin incompatibility. tell me your plugin list if you are going to continue to be unhelpful with this problem and blame the plugin. and ill do it for you

**Comment by Armin231** [comment]
> > > and I thing its a you problem, as your server also crashed when players get armor lolol. let me know what plugin that is and I can see about fixing that, and that's probably the issue for this too
> > 
> > 
> > We run the server via Pterodactyl if that means anything but that shouldn't really be causing any issues as every plugin works through there. It's definitely something in your code base.
> 
> again, im not saying your server is bad. im saying there is a plugin incompatibility, as im running this on a lowpowermac, and playing and having no issues, we also use akliz for our server, and no issues, and nowhere is German ™️ with no issues, im 100% certain its a plugin incompatibility. tell me your plugin list if you are going to continue to be unhelpful with this problem and blame the plugin. and ill do it for you

Tbh I also encountered the gui flicker. Like closing and repoing when leaving a tab

**Comment by MisterEpic** [comment]
> > > > > 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)
> > > > 
> > > > 
> > > > I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.
> > > 
> > > 
> > > you literally can't have enough skills for it to be tedious, I made it in such a way that you can only have like 5 maxed skills, or like 15 level 1 skills (which is a waste for everything)
> > 
> > 
> > Even with only 5 skills, having the ability to reduce clicks by 10-20 (entering each skill tree and unlearning them) would greatly reduce its tedious nature. Especially if players are regularly respecing
> 
> that's the point, I want them NOT to respect often, I want minimal respec'ing, but I feel the tedious nature if things is coming from the window speed

Understandable, but I believe your plugins immense depth lends itself to multiple different playstyles, and restricting players isn't any fun. What you've made here is awesome, and could allow players to play in multiple different but unique ways, and I don't think you should shy away from that.

**Comment by NextdoorPsycho** [comment]
> > > > and I thing its a you problem, as your server also crashed when players get armor lolol. let me know what plugin that is and I can see about fixing that, and that's probably the issue for this too
> > > 
> > > 
> > > We run the server via Pterodactyl if that means anything but that shouldn't really be causing any issues as every plugin works through there. It's definitely something in your code base.
> > 
> > 
> > again, im not saying your server is bad. im saying there is a plugin incompatibility, as im running this on a lowpowermac, and playing and having no issues, we also use akliz for our server, and no issues, and nowhere is German ™️ with no issues, im 100% certain its a plugin incompatibility. tell me your plugin list if you are going to continue to be unhelpful with this problem and blame the plugin. and ill do it for you
> 
> Tbh I also encountered the gui flicker. Like closing and repoing when leaving a tab

mmm well if it closes and opens in less than 50ms that's fine, but that's because im closing then opening but ill look into it

**Comment by NextdoorPsycho** [comment]
> > > > > > 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)
> > > > > 
> > > > > 
> > > > > I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.
> > > > 
> > > > 
> > > > you literally can't have enough skills for it to be tedious, I made it in such a way that you can only have like 5 maxed skills, or like 15 level 1 skills (which is a waste for everything)
> > > 
> > > 
> > > Even with only 5 skills, having the ability to reduce clicks by 10-20 (entering each skill tree and unlearning them) would greatly reduce its tedious nature. Especially if players are regularly respecing
> > 
> > 
> > that's the point, I want them NOT to respect often, I want minimal respec'ing, but I feel the tedious nature if things is coming from the window speed
> 
> Understandable, but I believe your plugins immense depth lends itself to multiple different playstyles, and restricting players isn't any fun. What you've made here is awesome, and could allow players to play in multiple different but unique ways, and I don't think you should shy away from that.

I don't think you have played with adapt outside of cheating. it's supposed to NOT be a skills plugin. it's an adaptation plugin. like you are mining for so long, and you can now just do it faster, or you are growing things for so long and now they do that for you. its supposed to feel like AID rather than a SKILLS plugin. Given, there are skills aspects, but that's not the goal

**Comment by NextdoorPsycho** [comment]
added a command, for the GUI, untested, but its there.

**Comment by MisterEpic** [comment]
> > > > > > > 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)
> > > > > > 
> > > > > > 
> > > > > > I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.
> > > > > 
> > > > > 
> > > > > you literally can't have enough skills for it to be tedious, I made it in such a way that you can only have like 5 maxed skills, or like 15 level 1 skills (which is a waste for everything)
> > > > 
> > > > 
> > > > Even with only 5 skills, having the ability to reduce clicks by 10-20 (entering each skill tree and unlearning them) would greatly reduce its tedious nature. Especially if players are regularly respecing
> > > 
> > > 
> > > that's the point, I want them NOT to respect often, I want minimal respec'ing, but I feel the tedious nature if things is coming from the window speed
> > 
> > 
> > Understandable, but I believe your plugins immense depth lends itself to multiple different playstyles, and restricting players isn't any fun. What you've made here is awesome, and could allow players to play in multiple different but unique ways, and I don't think you should shy away from that.
> 
> I don't think you have played with adapt outside of cheating. it's supposed to NOT be a skills plugin. it's an adaptation plugin. like you are mining for so long, and you can now just do it faster, or you are growing things for so long and now they do that for you. its supposed to feel like AID rather than a SKILLS plugin. Given, there are skills aspects, but that's not the goal

Even so, being able to switch between the way you "adapt" to various situations faster, would only be beneficial to the plugin's use. Like I mentioned above, you may want to adapt to combat situations differently then building situations, and being able to do that as fast as possible will be to the players liking.

**Comment by Armin231** [comment]
> > > > > > > > 4, I want to eventually fill the page with skills but, idk in the mean time I can add it, just seems strange to me ig, but I also made it so I know where everything is. Another reason I don't want to add that is because forgetting that you have something equip makes it feel like its a part of you and you don't even notice it (Why the plugin is called Adapt, and not MCMMO 2 or something like that)
> > > > > > > 
> > > > > > > 
> > > > > > > I get what you are saying here, but I'm just thinking of the players. In practice at higher levels, I think it would be extremely tedious to have to unlearn all skills 1 by 1. I think its better to think of it as "respeccing", as these players clearly know all the abilities and what they have equipped, and just want an easy method of changing skills without tediously having to unlearn each skill.
> > > > > > 
> > > > > > 
> > > > > > you literally can't have enough skills for it to be tedious, I made it in such a way that you can only have like 5 maxed skills, or like 15 level 1 skills (which is a waste for everything)
> > > > > 
> > > > > 
> > > > > Even with only 5 skills, having the ability to reduce clicks by 10-20 (entering each skill tree and unlearning them) would greatly reduce its tedious nature. Especially if players are regularly respecing
> > > > 
> > > > 
> > > > that's the point, I want them NOT to respect often, I want minimal respec'ing, but I feel the tedious nature if things is coming from the window speed
> > > 
> > > 
> > > Understandable, but I believe your plugins immense depth lends itself to multiple different playstyles, and restricting players isn't any fun. What you've made here is awesome, and could allow players to play in multiple different but unique ways, and I don't think you should shy away from that.
> > 
> > 
> > I don't think you have played with adapt outside of cheating. it's supposed to NOT be a skills plugin. it's an adaptation plugin. like you are mining for so long, and you can now just do it faster, or you are growing things for so long and now they do that for you. its supposed to feel like AID rather than a SKILLS plugin. Given, there are skills aspects, but that's not the goal
> 
> Even so, being able to switch between the way you "adapt" to various situations faster, would only be beneficial to the plugin's use. Like I mentioned above, you may want to adapt to combat situations differently then building situations, and being able to do that as fast as possible will be to the players liking.

The plugin hasn’t been released yet. While feedback is welcome. Bugs needed to be sorted out first before adding more and more to it. Atm there is no user base of adapt and therefore I would say there is no real necessarily to go in one or another direction for adapt

**Comment by Armin231** [comment]
For player feedback and discussions I recommend you to join the discord and start talking in the adapt channel rather than here

**Comment by NextdoorPsycho** [comment]
6: added
![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)

**Comment by TheekshanaA** [comment]
> 6: added ![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif) [ ![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif) ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif) [ ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)

Thank you looks good, any chance you can do /skills as an alternative if not we can make our own command to reroute to yours

**Comment by Armin231** [comment]
> > 6: added ![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >       
> >         [
> >           
> >             ![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >           
> >         ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >         
> >        [ ![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif) ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >       
> >         [
> >           
> >             ![CleanShot 2022-08-24 at 12 15 31](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >           
> >         ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/29320316/186470924-3e84b467-3b7a-4f31-a967-99ad0afe6a72.gif)
> 
> Thank you looks good, any chance you can do /skills as an alternative if not we can make our own command to reroute to yours

make your own cause /skills is probably used by a lot of other plugins therefore that wouldnt be a good idea

**Comment by NextdoorPsycho** [comment]
im not overwriting /skills for the same reason I don't want Iris to overwrite /I or /studio
Just added a Half-assed Note system, ill show in a sec

**Comment by NextdoorPsycho** [comment]
<img width="607" alt="CleanShot 2022-08-24 at 13 23 14@2x" src="https://user-images.githubusercontent.com/29320316/186483772-021dca53-77a9-40ef-8230-ba75b448a808.png">

@TheekshanaA k here you go

**Comment by TheekshanaA** [comment]
> <img alt="CleanShot 2022-08-24 at 13 23 14@2x" width="607" src="https://user-images.githubusercontent.com/29320316/186483772-021dca53-77a9-40ef-8230-ba75b448a808.png">
> 
> @TheekshanaA k here you go

Thanks mate, will you be adding any of the other features by any chance?

**Comment by NextdoorPsycho** [comment]
2 things remain from this issue request:
1: The annoying bit of them menu like taking a while (This is not a feature, im keeping it closing, but ill look into its Sliggish-ness if you know what I mean) 
2: The unsub from all button. Still mulling it over.

If you can make 2 issues for these, but just like give it a title, and link it here in the desc ill get to them when im home for now im closing this.

**Comment by MisterEpic** [comment]
> 2 things remain from this issue request: 1: The annoying bit of them menu like taking a while (This is not a feature, im keeping it closing, but ill look into its Sliggish-ness if you know what I mean) 2: The unsub from all button. Still mulling it over.
> 
> If you can make 2 issues for these, but just like give it a title, and link it here in the desc ill get to them when im home for now im closing this.

https://github.com/VolmitSoftware/Adapt/issues/45
https://github.com/VolmitSoftware/Adapt/issues/46
