### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by MusicTW** [VolmitSoftware/Adapt#429]
### Problem

console spamming warning message, can't open gui, can't earn skill exp anymore
Minecraft version is 1.19.3 but can't choose below

### Minecraft Version

1.19.2

### Adapt Version

1.9.2-1.19.4

### Log

https://pastebin.com/qTif452S    https://pastebin.com/yYxDLMqH

**Comment by MusicTW** [comment]
after I change adapt version to 1.6.2-1.19.3, it works

**Comment by NextdoorPsycho** [comment]
Latest spigot brok, fix incomming
