### ISSUE TITLE
no idea if this works... No it doesnt!

### ISSUE THREAD

**Issue by Armin231** [VolmitSoftware/Adapt#43]
This broke compiling adapt https://github.com/VolmitSoftware/Adapt/commit/0c1f9d7f499beeacc545e35ed6564b5f3567a4a4 lol

**Comment by NextdoorPsycho** [comment]
LMAO

**Comment by NextdoorPsycho** [comment]
Skank, it works now

**Comment by Armin231** [comment]
Its working. Thx
