### ISSUE TITLE
Error Failed to grant advancement skill_rift Reattaching!

### ISSUE THREAD

**Issue by ChrisTVH** [VolmitSoftware/Adapt#475]
### Problem

**Server version**
![image](https://github.com/VolmitSoftware/Adapt/assets/58376852/5244b4fd-6a76-45f5-a333-491277d9aa9d)

**Adapt Version**
1.14.0-1.20.4

**The error I want to report**
![image](https://github.com/VolmitSoftware/Adapt/assets/58376852/d873b9f1-fa26-4786-8f31-5e7d755cd135)

I want to emphasize that I have the SQL option enabled and this happens sometimes when a player enters the server, and the additional condition for this to be fulfilled, is that this may appear when I first start the server.

### Minecraft Version

1.2

### Adapt Version

1.14.0-1.20.4

### Log

https://mclo.gs/BkMc0pn

**Comment by CrazyDev05** [comment]
please update to 1.15.2
