### ISSUE TITLE
[Suggestion] ability to change the [Adapt] cmd prefix in chat in the locs or config.

### ISSUE THREAD

**Issue by illyrius666** [VolmitSoftware/Adapt#489]
### Adding, Removing, or Changing

Changing

### Type of Modification

see title

### What are you trying to modify

is have a server colorscheme i use and every plugin is adjusted to it except adapt. it would be nice to be able to change it here too.
![image](https://github.com/VolmitSoftware/Adapt/assets/28700752/67131a51-6b41-43c6-9ca6-64298108f214)

### Alternatives

none

**Comment by NextdoorPsycho** [comment]
We migrated the Adapt command system

**Comment by illyrius666** [comment]
yes but i still cannot adjust that adapt prefix, are you planning to add that or is it out of bounds? i just want to know so i can move on haha.

**Comment by NextdoorPsycho** [comment]
I don't know another plugin that keys you change that. I can but. It'll be next update

**Comment by illyrius666** [comment]
![image](https://github.com/user-attachments/assets/ceac7c3e-4fde-42c9-ba09-454031e1069b)
all these plugins except adapt allow me to do that

**Comment by illyrius666** [comment]
some have the setting in their config file others in the localization file
