### ISSUE TITLE
[Suggestion] gui item custom data

### ISSUE THREAD

**Issue by illyrius666** [VolmitSoftware/Adapt#491]
### Adding, Removing, or Changing

Changing

### Type of Modification

I want to be able to assign custom data to a item in the gui

### What are you trying to modify

so i can have custom icons for the items based on my resourcepack.
![image](https://github.com/VolmitSoftware/Adapt/assets/28700752/5113a512-c796-4345-83bf-ed6b745662e8)

### Alternatives

none

**Comment by NextdoorPsycho** [comment]
This was not closed because this is something I want to do

**Comment by illyrius666** [comment]
@NextdoorPsycho o yeah sorry haha, i didnt see any label so i thought i was ignored

**Comment by illyrius666** [comment]
@CrazyDev05 @NextdoorPsycho this is completed right? so we can close this as done?

**Comment by illyrius666** [comment]
bump

**Comment by illyrius666** [comment]
> @CrazyDev05 @NextdoorPsycho this is completed right? so we can close this as done?

bump
