### ISSUE TITLE
[BUG/FEATURE] Mouse cursor bug resetting to the center of the gui on going back

### ISSUE THREAD

**Issue by illyrius666** [VolmitSoftware/Adapt#508]
### Problem

1. Install Adapt
2. Navigate through the GUI
3. Go back by one
4. Observe your mouse cursor being reset to the center of the gui.

### Solution (if any)

iam not skilled enough to provide a direct solution, but i have seen that commandpanels did achieve fixing it, so its not impossible, its more a question if we want to fix it and when.

### Minecraft Version

1.21

### Adapt Version

Adapt-1.15.2-1.19.2-1.21.1

### Log

https://mcpaste.io/ebca96183a2a93ec

**Comment by CrazyDev05** [comment]
the way to fixing this is to make all guis of a player be one inventory
which would require a rewrite of the guis

**Comment by illyrius666** [comment]
> the way to fixing this is to make all guis of a player be one inventory which would require a rewrite of the guis

do you think its worth it? it will make the gui be more smooth, which would add to the player experience. i mean it doesnt have to be a priority task?

**Comment by CrazyDev05** [comment]
i may have found a solution that should work for use without a rewrite
