### ISSUE TITLE
[FEATURE] same lang style for GUI & Advancements as the command system

### ISSUE THREAD

**Issue by illyrius666** [VolmitSoftware/Adapt#510]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to use the same styling by default for the GUI & Advancements like the cmd system.

### What are you trying to modify

The way I would implement this is by changing its style, to match with that of the cmd system. i find the styling very user friendly and i think we can expand that to all concepts of the plugin.
iam going to try and do this myself, since i want to contribute to it a bit.

this is more a thing to have as default, as server owners can obv adjust it to their liking.

### Alternatives

none.

**Comment by CrazyDev05** [comment]
wdym with styling?

**Comment by illyrius666** [comment]
> wdym with styling?

you know how when you do /adapt you have this nice blue colored style for the text, and then certain things like brackets have a different color, that style should be applied to other things too. as a default obv. like how it is styled now is plain compared to the command system text.

**Comment by CrazyDev05** [comment]
> you know how when you do /adapt you have this nice blue colored style for the text, and then certain things like brackets have a different color, that style should be applied to other things too. as a default obv. like how it is styled now is plain compared to the command system text.
hmm, what I could do is to parse the & / § colors with the special gradient but keep mini message to overwrite it if needed

**Comment by CrazyDev05** [comment]
I added it with a setting disabled by default as it seems to be messing with the other localizations
