### ISSUE TITLE
Commands Internal Error

### ISSUE THREAD

**Issue by Omarlatif** [VolmitSoftware/Adapt#57]
### Problem

1. Install Adapt...
2. Try any of the commands
3. "An internal error occurred while attempting to perform this command"
4. Error in console

Please note that /adapt test and /adapt open gui are unaffected.
Server is running Purpur 1.19.2 #1770

### Minecraft Version

1.19

### Adapt Version

Adapt 1.0.4

### Log

https://mclo.gs/PzLI6h4

**Comment by Armin231** [comment]
@Omarlatif its already mentioned here https://github.com/VolmitSoftware/Adapt/issues/49 so you can close this
