### ISSUE TITLE
Giving/receiving mob damage in the nether crashes the server

### ISSUE THREAD

**Issue by Omarlatif** [VolmitSoftware/Adapt#58]
### Problem

1. Install Adapt...
2. Go into the nether
3. Attack/get attacked by a mob
4. Wait 10-15 seconds
5. Server crash

Purpur 1.19.2 #1770
I've tried with and without Adapt, it only crashes when Adapt is installed.

I know you guys said to paste a full log, unfortunately the log does not contain the crash. Instead i will be posting the Error from console and the crash report file.

### Minecraft Version

1.19

### Adapt Version

Adapt 1.0.4

### Log

Error: https://pastebin.com/aRk9R2km -- Crash Report: https://mclo.gs/q4HVABc

**Comment by NextdoorPsycho** [comment]
Fixed
