### ISSUE TITLE
Nature's Touch

### ISSUE THREAD

**Issue by Raesak** [VolmitSoftware/Adapt#6]
This skill tree will be similar to MCMMO's "Taming" & "Call of the Wild".

It will give players the ability to spawn a configurable amount of allied (tamed) mobs specified in the config, with support for mob plugins like MythicMobs.

_First, there should be an option in the config for whether the mob abilities will also be applied to mobs that players tame naturally (like wolves, horses, ETC), or if these abilities will ONLY apply to naturally tamed mobs (if we prevent the player from summoning them).
It should also be configurable, if the abilities apply to naturally tamed mobs, if the maximum amount of summoned mobs also applies to the amount of mobs that the player can tame.
(For example if we configure that the player can only spawn 3 wolves, they cannot have more than 3 tamed and summoned wolves).

There should also be an option in the config to outright prevent the player from being able to tame specified types of mobs._

### How It Works:
Each configured mob will have its own configurable spawn condition (including no condition at all, meaning the mob would have to be tamed naturally), configurable amount spawned per condition, max amount able to be alive at once (which also limits how many can be tamed).
If a mob is mountable, also configurable if specific Adapt abilities can be used while mounting it (if those abilities are able to be used while mounting).

Each configured mob will have its own level, or skill line. For example, if one of the configured mobs is a Horse. We can configure the max level, stats & abilities at each level.
The abilities will ONLY be available, once allied to the player, for mobs that meet those conditions specified in the config. Let's call them "allied mobs" for the time being, for convenience.

### Barn & Horn:
Before we continue, there are two important abilities that need to be discussed first. These abilities may require a "Server:" setting in the config to configure the name of each server that Adapt is installed on, assuming that multiple instances of the plugin will be connected to the same database:

1. Barn:
This ability is used via command (a short command). It sets a location for allied mobs to be teleported to when not in use for a specified amount of time. This command can ONLY be set in areas where the player can build. It can also hook into various claim plugins (like Lands, Residence, Faction plugins, ETC). If the player loses permission to build there, the Barn location will be deleted.
|
An allied mob can become inactive if the player dies, or is afk, or in a different world, ETC.
Allied mobs can be manually sent to the Barn location via command (the same command used to send the barn, suffixed with the name of the allied mob, or vise versa).
(If multiple allied mobs have the same name, the command will be activated for all with the same name)

Barn can be configured to be per server, and per world, but servers and worlds can also be configured to be linked together.
For example, in the config I can set the barn location for "world" to be exclusive, but I can also link it to "world-nether". This means that the barn location for "world" and "world-nether" are the same, and allied mobs will automatically or manually be teleported there.
If a world/server is removed from the list of worlds that the Barn location can be set, ALL barn locations in that world/server will be deleted.
|
It MUST be configurable if allied mobs in unlinked Barn worlds/servers will be counted together towards the total amount of allied mobs that the player is allowed to have.
If not, then when worlds/servers world is linked and the player ends up with more than the max amount of allied mobs, either the allied mobs will be killed at random until the max amount is reached, or simply all of the allied mobs will be killed instantly.

2. Horn:
Horn is also used via command, to teleport allied mobs to the player. Pretty much the same rules as Barn otherwise.

Horn & Barn will use the same list of linked worlds and blacklisted worlds for the commands, but Horn will have the configurable option to be used in places where the player cannot build.

____________________________

Both Horn & Barn can be configured to be completely disabled, or disabled individually.

Anyway, It is also configurable if the allied mob level (skill line) applies for all mobs of each type, or each individual mob.
For example, if the player levels up horse to 50, will ALL horses he claims be level 50, or only that specific one?
If it is configured for allied mob level to be applied individually, when the horse dies, all progress for the mob is lost and the player will start over.

There should be a number of premade stats and abilities for the server owner to choose from, to be applied to allied mobs at the specified level. The full list of these abilities should be on the wiki, and of course, some abilities can only be applied to certain types of mobs. For example, attacking abilities cannot be applied to mobs that don't attack (like horses). All of that info is on the wiki.
Also, all abilities are configurable in the config, whether or not the player is able to disable certain abilities after the allied mob attains those abilities:

### Abilities:
Emergency Retreat:
The allied mob has a configured chance to automatically teleport to the Barn location when their health drops to a configured amount.
(Barn world/server rules apply)

Honorable Loyalty:
The allied mob has a configured chance to automatically teleport to the player (Horn) when the player's health drops to a configured amount.
(Horn world/server rules apply)

Steadfast Loyalty:
The allied mob, when in a certain block radius of the player, has a configured chance to swap locations with the player and die in the case that the player receives fatal damage. The player is instead granted the remainder of the allied mob's HP (configured if it is added to the player's HP or as a temporary Absorption effect for a specified amount of time. Cannot grant more than the max amount of HP). And a configurable amount of buffs for the player, lasting a configurable amount of time.

Rage:
The allied mob has a configured chance to activate this ability, hitting the enemy with configured knockback strength, and a configured cooldown.

Wild Slash:
The allied mob has a configured chance to activate this ability, causing damage over time to the player for a configured amount of ticks.

___________________

Those are just some examples of abilities. Any amount can be added.

The stats that can be configured should include: health, damage, speed, armor.

**Comment by NextdoorPsycho** [comment]
so this in terms of scope is very large. 

Adapt is intended to be something that you just notice passively, or something that you just happen to stumble across. you should not need to have to read a memoir to be able how to understand how to control the entire hoard of mobs, and i dont want their to be any UI elements that are added and Bars or anything, it deems like it would taka away from the "vanilla" experience that we are aiming for. ie: Every server should be able to consider it, and not have these complex esk of systems
