### ISSUE TITLE
Hardcore & Reward Mechanics

### ISSUE THREAD

**Issue by Raesak** [VolmitSoftware/Adapt#7]
It's hard to give a good recommendation for this since the available info on Adapt is very limited, but I figure it's best to get this idea in early.

I recommend some kind of Hardcore type mechanic similar to what MCMMO has. For example when enabled, if the player dies they lose a configurable amount of levels.
Except you guys can go one step further, and also add special rewards for when players kill other players (there will need to be restrictions preventing abuse of that).

There are many types of configurable penalties that can be added for when players die.
Losing levels, locking abilities, ETC.

There are also many types of configurable rewards for when players kill other players.
EXP boosts, level tokens (like tokens used to increase levels), ETC.

That type of mechanic will be especially good for survival servers to raise the stakes of dying and the value in PvP.

**Comment by NextdoorPsycho** [comment]
ok so!

There are XP boosts now, 
There are Bonuses like fall 100 times, walk 1kilometers etc... and they reward things.
we COULD add an advancement system that just deducts points from a player if something happens, but imo thats kinda toxic, but we have ways CURRENTLY implemented to make this happen

**Comment by NextdoorPsycho** [comment]
Added, Lose everything On Death
