### ISSUE TITLE
Levitation mechanic

### ISSUE THREAD

**Issue by MineForce899** [VolmitSoftware/Adapt#8]
If the player is on the ground, then levitation is charged for him. When the levitation is fully charged, the player can press the space bar twice (like double jumps on some servers) to activate the levitation effect. During this effect, the player rises about 5 blocks up and stands there until the levitation is discharged. After that, the player will slowly fall using the slow fall effect. The player can also independently stop levitation by pressing SHIFT during this effect.

**Comment by NextdoorPsycho** [comment]
I implemented something like this in the Rift category, the person is lifted for 5 seconds then teleported, but the lift mechanic is what im referring to (has a neat particle effect)
