### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by Omarlatif** [VolmitSoftware/Adapt#99]
### Problem

1. Install Adapt...
2. Join the server
3. Server crashes

Nothing appears in the log file, so once again, I must send the crash log.
Purpur 1.19.2 #1770

### Minecraft Version

1.19

### Adapt Version

1.0.6

### Log

Error: https://pastebin.com/Qpyfpjhm --- Crash report: https://mclo.gs/VFH0w8p

**Comment by Armin231** [comment]
> I believe I fixed it by deleting all player datas

If it happens again let us know. Where those players just casually playing or did you used the adapt command for giving exp to test skills?

**Comment by Omarlatif** [comment]
It's just me and another player testing out the plugin. I didn't use the adapt command to give exp or levels, only edited the file a few versions ago... I think on version 1.0.4 - I will continue to look around to hopefully provide information and assist with the plugin

**Comment by Armin231** [comment]
We appreciate that. Adapt is fairly new and therefore bugs are unwanted but expected, and that’s why the dev will fix them as soon as they appear. This way everyone will get a amazing experience as it should be.

**Comment by NextdoorPsycho** [comment]
> I believe I fixed it by deleting all player datas

im going to close this for now, please tell me if you find out what is causing this and if you do i can fix it
